### ISSUE TITLE
Support API Gateway

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1077]
#### Description

Add Cortex API configuration to configure AWS API Gateway, so that users can have out-of-the-box access to trusted SSL certificates.

**Comment by deliahu** [comment]
@puhoshville Yes that's a great idea, I'll add a separate ticket for that!

One thing that comes to mind is the distinction between REST and HTTP API Gateways. HTTP is the newer product, and from what I've seen it seems that AWS is recommending that new applications start with HTTP instead of REST. However, at least as of today, HTTP APIs [don't support caching](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html) (only REST APIs do). Since it's still possible for users to manually create a REST API gateway and configure caching, we are considering implementing HTTP API Gateways out-of-the-box to support typical use cases. Hopefully AWS brings HTTP APIs to feature parity with REST APIs soon, or if not, once we've implemented HTTP API Gateway out-of-the-box, we could add an option to use REST instead (and then expose the cache configurations in the cortex API configuration).

**Comment by puhoshville** [comment]
@deliahu oh, didn't mention that HTTP API doesn't support caching. 
Maybe using [AWS SAM](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html) syntax can simplify/unify API Gateway usage? It supports both [REST API](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html) and [HTTP API](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html). Not very familiar with cortex architecture but probably AWS SAM can be used.

**Comment by deliahu** [comment]
Thanks @puhoshville, we will check out SAM
