### ISSUE TITLE
Avoid installing Python packages on each Cortex deploy

### ISSUE THREAD

**Issue by MrRace** [cortexlabs/cortex#1086]
I need other python packages,so i use the requirements.txt file. But I find each time of cortex deploying would install the packages in requirements.txt file, that consuming many time. Is there a way to fix my pain point? Could I just install the packages I need once time? Thanks a lot!

**Comment by RobertLucian** [comment]
The `requirements.txt` file has been added to make it easy for users to install Python packages without dealing with the hassle of creating custom Dockerfiles for each new modification. 

With that in mind, here's how you can create a custom Dockerfile image with your preferred Python packages. Before anything else, check what's your current image in `predictor:image` field - you can do that with `cortex get <my-api>`. To choose from one of the base images, check this out [here](https://docs.cortex.dev/deployments/system-packages#custom-docker-image).
```Dockerfile
# test base image, can be any of the other 4
FROM cortexlabs/python-predictor-cpu-slim:0.17.0

COPY requirements.txt /etc/pip/requirements.txt

# /bin/bash is required
RUN /bin/bash -c "pip install --no-cache-dir -r /etc/pip/requirements.txt"
```

Will this make it easier for you?

**Comment by MrRace** [comment]
@RobertLucian  Thanks for your reply.  After building a new image, I set predictor->image value as the new builded image in the `cortex.yaml` . When running  `cortex deploy`  comes the error below:
```
error: /home/liujiepeng/IntentClassification/logistic_regression/cortex/cortex.yaml: gbm-classifier: predictor: image: ljp/cortex-python-predictor-cpu is not accessible
Error response from daemon: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```
What should I do to fix it?

**Comment by deliahu** [comment]
@RobertLucian can correct me if I'm wrong here, but I believe currently, the image must be pushed to a public repo in Dockerhub, or a private repo in ECR. We added this check because it is necessary to ensure that the image is accessible when running Cortex in AWS. However, I created https://github.com/cortexlabs/cortex/issues/1094 for us to look into whether we can allow local docker images (only when running Cortex locally).

In the mean time, the easiest solution is to push your image to Dockerhub, something like this (assuming you own the `ljp` repository in Dockerhub):

```text
docker push ljp/cortex-python-predictor-cpu
```

**Comment by RobertLucian** [comment]
@MrRace with #1104, you will be able to get rid of `/bin/bash -c` before the pip command. Have a look at this example:
```Dockerfile
# test base image, can be any of the other 4
FROM cortexlabs/python-predictor-cpu-slim:0.17.0

COPY requirements.txt /etc/pip/requirements.txt
RUN pip install --no-cache-dir -r /etc/pip/requirements.txt
```
