### ISSUE TITLE
Multi-armed bandit

### ISSUE THREAD

**Issue by puhoshville** [cortexlabs/cortex#1089]
Very new to the cortex but already fall in love with it! Thank you for the great work! 🥇 
#### Description

It will be great to have an option to host different (but with the same API) models in an isolated manner behind a load balancer with configurable weights. Unfortunately, I didn't find how to implement this out-of-the-box.

#### Motivation

This feature will let DS and MLOps implement a multi-armed bandit.
Multi-armed bandits let you develop models continuously with no fear that your new model will perform not as good as the previous one.

The supported way for [hosting multi-model endpoint](https://docs.cortex.dev/guides/multi-model) doesn't let you isolate models. It may be very tricky to pack two large models in one service/container and maybe not cost-effective. But it is a very common case when you're dealing with DL.

#### Additional context
Of course, a multi-armed bandit needs additional feedback processing service, but this can be implemented only by MLOps with all essential knowledge of business processes. 

Scheme:
![cortex-multi-armed-bandit](https://user-images.githubusercontent.com/6560448/83287240-4b0abb80-a21c-11ea-9e64-5619225fc767.jpg)

**Comment by deliahu** [comment]
@puhoshville Thanks for the kind words, I'm glad you're liking Cortex!

Yes, I think this would be a useful feature. Our infrastructure is already mostly set up to support this, so it may not be too much effort; with Istio, we can route to multiple deployments from a single endpoint based on weights.

If I understand correctly, you are saying that the user would be responsible for calculating which percentage of requests to send to each model, and that Cortex would only provide the API to update these percentages, is that correct?

I'd be happy to jump on a call if you'd like to discuss, feel free to email me at david@cortex.dev if you are interested.

**Comment by puhoshville** [comment]
> If I understand correctly, you are saying that the user would be responsible for calculating which percentage of requests to send to each model, and that Cortex would only provide the API to update these percentages, is that correct?
Yes, it's absolutely correct!
