### ISSUE TITLE
Deployemnts with conda-packages fail in 0.17.0

### ISSUE THREAD

**Issue by dsuess** [cortexlabs/cortex#1100]
#### Version

0.17.0

#### Description

Deployments with `conda-packages.txt`, which worked fine in 0.16.0, hang on installing conda packages.

#### Steps to reproduce

1. Create a python-predictor-gpu deployment with `conda-packages.txt`
2. Deploy to local environment

#### Expected behavior

Deployment goes up.

#### Actual behavior

Hangs at this screen (shown through `cortex logs`):

```
The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  ffmpeg             conda-forge/linux-64::ffmpeg-4.2.3-h167e202_0
  freetype           pkgs/main/linux-64::freetype-2.9.1-h8a8886c_1
  gmp                conda-forge/linux-64::gmp-6.2.0-he1b5a44_2
  gnutls             pkgs/main/linux-64::gnutls-3.6.5-h71b1129_1002
  lame               pkgs/main/linux-64::lame-3.100-h7b6447c_0
  libiconv           pkgs/main/linux-64::libiconv-1.15-h63c8f33_5
  libpng             pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  nettle             pkgs/main/linux-64::nettle-3.4.1-hbb512f6_0
  openh264           conda-forge/linux-64::openh264-2.1.1-h8b12597_0
  x264               conda-forge/linux-64::x264-1!152.20180806-h14c3975_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2020.4.5~ --> pkgs/main::ca-certificates-2020.1.1-0
  certifi            conda-forge::certifi-2020.4.5.1-py36h~ --> pkgs/main::certifi-2020.4.5.1-py36_0
  openssl            conda-forge::openssl-1.1.1g-h516909a_0 --> pkgs/main::openssl-1.1.1g-h7b6447c_0
```

#### Suggested solution

Add `-y` option to `conda install`. See PR committed.

**Comment by RobertLucian** [comment]
@dsuess I'm able to reproduce this. Would you say this bug is a blocker for you? We can create a patch release specifically for this issue in case you need it ASAP.

**Comment by dsuess** [comment]
That's okay, if the docker images are rebuilt, I can work off master for testing. Given the previous release cycle, a new release should come out in the next 1--2 weeks?

**Comment by deliahu** [comment]
@dsuess thanks for bringing this to our attention, and for contributing the fix!

I just spoke with the team, and we think it does make sense to make a patch release for this. There is one other small fix that we're working on which we may finish soon, so we'll hold off for a day to see if we can get that in too, and then we'll release 0.17.1.

**Comment by deliahu** [comment]
Also, in case it's relevant to you, this issue only seems to happen locally (it doesn't get stuck on AWS)

**Comment by dsuess** [comment]
I can confirm that it's fixed on the `master` branch for me. Looking forward to 0.17.1
