### ISSUE TITLE
Add support for private image registries

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1113]
#### Description

At the moment, users can only use public images hosted on DockerHub or images hosted on AWS ECR. This feature would add support for private registries as well (i.e. DockerHub), accessible through the use of access tokens.

#### Motivation

For users who want their images to be private and yet not be necessarily hosted on AWS ECR.

**Comment by deliahu** [comment]
Potential workaround until this is implemented:

* use a public registry
* use a private ECR registry
* install required dependencies via one of [these approaches](https://docs.cortex.dev/advanced/python-packages) for Python dependencies and [`dependencies.sh`](https://docs.cortex.dev/advanced/system-packages#bash-script) for system dependencies.
