### ISSUE TITLE
Is it possible to launch more than one cortex cluster on the same machine?

### ISSUE THREAD

**Issue by javithe7** [cortexlabs/cortex#1118]
Hi everyone

1) I suppose it is possible to launch more than one cortex cluster on the same machine using a different cluster.yaml for each one, am i right?.

2) In the case of having been able to launch more than one cluster on the same machine, how can I indicate in which cluster I want my model to be deployed?

Thanks

**Comment by deliahu** [comment]
Hi @javithe7, thanks for reaching out!

Yes, it is possible to launch multiple cortex clusters from the same machine using a different `cluster.yaml`, and you can specify which one to use when deploying. Here is an [example](https://docs.cortex.dev/miscellaneous/environments#example-multiple-clusters) (or see [this example](https://docs.cortex.dev/miscellaneous/environments#example-multiple-clusters-if-you-omitted-the-env-on-cortex-cluster-up) if you already have multiple clusters running).

**Comment by RobertLucian** [comment]
@javithe7 there's one assumption I have to make about both of your questions and that is: by same machine, I take you're referring to the place where the Cortex CLI is installed and not where the actual cluster is running. 

With that out of the way, let me answer your questions here:

1. Yes, that's correct, you can spin-up multiple clusters. There's no limit on how many you can have. For that to be possible, you have to come up with unique names for your environments - each environment can manage one cluster. This environment is created upon spinning up the cluster by adding `--env` option to your command. When spinning up a cluster, the default name of the environment is `aws`.

1. Assuming you have deployed 2 clusters in 2 environments called `cluster1` and `cluster2`, you can make it such that APIs are deployed to `cluster1` cluster by running `cortex deploy --env cluster1` and respectively, `cortex deploy --env cluster2` for `cluster2`.

My suggestion is to go through this [page that describes Cortex environments](https://docs.cortex.dev/miscellaneous/environments) and give it a read.

**Comment by javithe7** [comment]
@deliahu @RobertLucian  Thank very much to both of you, that was exactly what i was asking for.
But after knowing this, a new doubt persists. Is it possible to deploy models in a cortex cluster that was launched with the cortex cli from a different machine ?. 
Imagine that I launch my cortex cluster with a cluster1.yaml and then deploy a model, all of it using my computer. If my computer suddenly dies, can I somehow access that same cluster from another cli on a different computer?

**Comment by deliahu** [comment]
@javithe7 yes this is possible, and we will add it to the environments documentation soon!

You can use the [`cortex configure`](https://docs.cortex.dev/miscellaneous/cli#env-configure) command on your other machine, and it will prompt you for the information necessary to connect to your cluster.

You could also copy over `cluster1.yaml` and run `cortex cluster info --config cluster1.yaml --env cluster1` which will automatically configure the "cluster1" environment in your cli .

**Comment by deliahu** [comment]
@javithe7 I have created https://github.com/cortexlabs/cortex/pull/1127 to add this information to the documentation ([here it is in markdown](https://github.com/cortexlabs/cortex/blob/34c26948b8e95620369a998c9537b0018157989e/docs/miscellaneous/environments.md#example-configuring-the-cortex-cli-on-a-new-machine-after-your-cluster-is-running)). Thanks for bringing it to our attention!

Also, when adding this section, I realized that I made a mistake in my previous message: I wrote `cortex configure`, but it should have been `cortex env configure`. The `cortex cluster info` command should work as I wrote it.

Were you able to configure the CLI on your new machine?

**Comment by deliahu** [comment]
@javithe7 I'll close this issue since I believe it's been addressed. Feel free to reach out if you have more questions.

**Comment by javithe7** [comment]
Hi @deliahu , thanks a lot for your help, this method worked for me.
Although I know that the issue is closed, I have a little final doubt. When a cluster was created using an old version of cortex (e.g 0.14), you can't access it using an updated cortex cli (e.g 0.17).
I suppose it is normal and that the only way would be to access it from a cli of the old version, or to create a new updated cluster, right?

 `error: cluster_cortex_1.yaml: image_manager: the specified image (cortexlabs/manager:0.14.0) has a tag (0.14.0) which does not match your Cortex version (0.17.1); please update the image tag, remove the image registry path from your configuration file (to use the default value), or update your CLI `

**Comment by RobertLucian** [comment]
> I suppose it is normal and that the only way would be to access it from a cli of the old version, or to create a new updated cluster, right?

@javithe7, yes you are correct!
