### ISSUE TITLE
Use official version of Kubernetes Cluster Autoscaler image

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1120]
#### Description

Change to official CA image (in `images/cluster-autoscaler`) when it will be possible.

#### Motivation

Because we're rolling on a customized (unofficial) version of CA. In order to migrate to the official version, https://github.com/kubernetes/autoscaler/issues/3095 must be fixed first. This is required for Inferentia.

#### Additional context

The current CA is a customized version called 1.16.6 of 1.16.5 that has had https://github.com/kubernetes/autoscaler/pull/3110 cherry-picked into it.

**Comment by deliahu** [comment]
https://github.com/kubernetes/autoscaler/issues/3109 has been resolved (by https://github.com/kubernetes/autoscaler/pull/3185), so perhaps we can resolve this with the next cluster autoscaler release
