### ISSUE TITLE
Add YOLOv5 example in PyTorch

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1130]
#### Description

Add YOLOv5 example using the PyTorch implementation from https://github.com/ultralytics/yolov5.

The example should support prediction for video or image-based formats.

**Comment by dsuess** [comment]
I am happy to give this a shot as I've got some experience with both this particular model in ONNX and video-predictions in Cortex. 

What kind of output did you envision for the video part? Should we add a simple tracker and return tracks?

**Comment by RobertLucian** [comment]
@dsuess yes, you can go ahead with this one. If you've got any questions along the way, please don't hesitate to give us a shout. I think going with the tracks (bounding boxes) overlayed over the actual video should be more interesting to the end-user when it's run. Otherwise, a client would be needed to draw the bounding boxes. What do you think?

I think a good template would be this example:
https://github.com/cortexlabs/cortex/tree/master/examples/keras/document-denoiser

Thanks!

**Comment by dsuess** [comment]
Ok, I'll just start with overlaying the video/image first and add tracking later.
