### ISSUE TITLE
Load local model

### ISSUE THREAD

**Issue by MrRace** [cortexlabs/cortex#1137]
For a local model, I want to load it in my `predictor.py`. I use the `print(os.path.abspath('.'))` to know its path is `/mnt/project` in the Docker, so if I directly load my model with absolute path of the machine, for example `load('/home/ljp/models/mymodel.pkl')`, it can not find the model naturally. I can just put the model in the same directory with `predictor.py` , is there other elegant solutions?  Maybe I have many models, different dockers should share with these models. Thanks a lot!

**Comment by vishalbollu** [comment]
@MrRace It sounds like you are using PythonPredictor to deploy your models locally. You have correctly noticed that local models can be used with the PythonPredictor by placing the model in the same folder or in a subdirectory of the folder containing your `predictor.py`. The mounting behaviour isn't exactly associated with your predictor.py, but rather the location of your `cortex.yaml`. Before Cortex runs your API locally, it mounts the directory containing your `cortex.yaml` to `/mnt/project`. 

If you multiple APIs that share models you could have a `models` directory in the same directory as `cortex.yaml` (or in a subdirectory of the folder containing your cortex.yaml).

```
my_project
├── cortex.yaml
├── predictor_a.py
├── predictor_b.py
└── models/
    ├── model1
    ├── model2
    └── model3
```

The model folder would be mounted into all APIs defined in that `cortex.yaml` file.
In your predictor implementations, you could load your models using `load('./models/model1')`, `load('./models/model2')`.

**Comment by deliahu** [comment]
I'll go ahead and close this issue, feel free to reach out if you have additional questions
