### ISSUE TITLE
Support for native Kubernetes clouds

### ISSUE THREAD

**Issue by NikPaushkin** [cortexlabs/cortex#1145]
#### Description

We've built the first (as we think) native Kubernetes provider [puzl.ee](https://puzl.ee). Each user gets own separate namespace and can run pods and volumes directly instead of using cloud instances with managed Kubernetes. 
Since user has an access to Kubernetes API, maybe this option can be supported by cortex: user just need to provide their kubeconfig and work with any Kubernetes cluster using cortex. We could implement cortex operator from our side and it will be the first native integration.

#### Motivation

Since you don't need to manage any cloud instances, support can be added much easier: only abstract Kubernetes API option needed to be integrated. Also it can give users much cheaper options.

**Comment by ospillinger** [comment]
Thanks for reaching out, puzl.ee sounds cool! We are focused on AWS for now but we'd be happy to advise if you want to build the integration on your end.

**Comment by NikPaushkin** [comment]
@ospillinger Glad to hear your feedback! Did I get it right, that you could accept our pull request, if we do?

**Comment by ospillinger** [comment]
We appreciate contributions but we can't commit to accepting any pull request. I'd be happy to set up some time to chat to make sure we're on the same page. Feel free to email me at omer@cortexlabs.com
