### ISSUE TITLE
Returned information by the cli in a different way than text by console

### ISSUE THREAD

**Issue by javithe7** [cortexlabs/cortex#1160]
Hi everyone

Is it possible to receive the information resulting from using the CLI commands, in a json style format or similar?

My goal is to process that information automatically to be able to extract deploy information and check the models displayed status.

Thanks

**Comment by deliahu** [comment]
@javithe7 There is not currently a way of doing this, but it's something we can look into! I created https://github.com/cortexlabs/cortex/issues/1161 to track this.

Which command(s) other than `cortex get` would you want to support this option? Also, is json your preferred format?

**Comment by javithe7** [comment]
Especially `cortex get` and  `cortex model-name` could be good options, also the `cortex cluster info` command, when you want to take a look in the configuration of a cluster could be useful. 
Yes, json is a really good election for this task.
@deliahu Thanks a lot for considering the implementation of this functionality.

**Comment by deliahu** [comment]
@javithe7 sounds good, thanks!

I'll go ahead and close this question, since we have filed https://github.com/cortexlabs/cortex/issues/1161
