### ISSUE TITLE
Support json output for CLI commands

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1161]
#### Description

Add a flag (e.g. `--json`) to certain CLI commands to output the response in structured json format.

#### Questions

* Which commands should support this? Definitely `get`; any others?

_suggested by https://github.com/cortexlabs/cortex/issues/1160_

**Comment by RobertLucian** [comment]
A possible alternative to mentioning the output format is: have an `-o/--output` option, with the allowed values being `json`, `yaml`, and `text`. `text` would be the default value so that the current output format is being kept.

**Comment by deliahu** [comment]
Thanks @zouyee, yes this one is up for grabs; let us know if you have any questions about this or if you'd be interested in discussing any of the design.
