### ISSUE TITLE
Is an instance starts spinning only on users' request, or is it always running?

### ISSUE THREAD

**Issue by timsoraro** [cortexlabs/cortex#1168]
Thanks for the awesome repo!

I didn't quite understand if it's possible to spin a new instance only when a user sends a request or whether (at least one)  instance is always running? Because the former will require some form of a separate (but probably cheap) server.

**Comment by vishalbollu** [comment]
Hi @timsoraro Currently scaling a replica down to 0 is not possible. You can configure the minimum number of replicas for your API to minimize cold starts. The lowest you can configure the min value is 1. As you've mentioned, in order to scale down to 0, a mechanism is required to queue the request until the API becomes available.

It would be helpful if you could share your use case for APIs scaling down to 0 replicas in a production setting. Do you expect there to be a long gap between requests such as a request for batch inference once every 2 hours? Or perhaps your API only receives requests during certain time periods like from 9 AM to 5 PM so you don't need an API running at night.

**Comment by timsoraro** [comment]
Hi! @vishalbollu, sorry for my quite basic understandings, I'm just digging into your docs and I'm not knowledgable in Devop. What does a replica mean? Is it the sort of basic CPU that manages the (let's say) powerful GPU instances that run the model? Or am I not getting the structure right?

If so, I was mostly curious, and secondly, because my app is still under the radar I was wondering about it since I'm not getting many requests yet.

Also, I can't quite grasp the entire infrastructure I'd use and, much more importantly, how much I'm going to pay for everything. Can you break it down for me approximately? From my understanding there's:
1. The basic instance that manages the entire thing (or are there more than 1? Is that EKS?)
2. EC2 instance, either spot/on-demand.
3. ?

Please correct me if I'm wrong, I'm trying to understand this better.

Thanks!

**Comment by vishalbollu** [comment]
@timsoraro No worries! A replica is 1 copy of a server/worker. In the context of Cortex, it is one copy of a Cortex predictor that serves your model. You can specify how much [compute resources](https://docs.cortex.dev/deployments/compute) each replica needs in the `compute` section of your [API configuration](https://docs.cortex.dev/deployments/api-configuration). Multiple replicas can be scheduled onto an EC2 instance depending on the compute requirements per replica and the EC2 instance chosen for your Cortex cluster.

Cortex autoscales replicas based on incoming traffic and the autoscaling configuration and Cortex autoscales the number of EC2 instances based on the number of replicas that need to be scheduled and their compute requirements.

You can get a breakdown of the different AWS resources used by Cortex and their price by defining a [cluster configuration](https://docs.cortex.dev/cluster-management/config) file and running `cortex cluster up -c cluster.yaml`. You will be prompted for confirmation after the pricing information has been displayed so you can try different configurations and get their prices without actually spinning up a cluster.

You should get an output like this:
```
aws resource                              cost per hour
1 eks cluster                             $0.10
0 - 5 t3.medium instances for your apis   $0.0125 - $0.0416 each (varies based on spot price)
0 - 5 50gb ebs volumes for your apis      $0.007 each
1 t3.medium instance for the operator     $0.0416
1 20gb ebs volume for the operator        $0.003
2 network load balancers                  $0.0225 each

your cluster will cost $0.19 - $0.43 per hour based on cluster size and spot instance pricing/availability
...
would you like to continue? (y/n): 
```

You can find an overview of the high-level Cortex infrastructure [here](https://docs.cortex.dev/miscellaneous/architecture).

Feel free to let us know if there are any sections of the documentation that can be improved to provide more clarity.

**Comment by timsoraro** [comment]
Thanks for your elaborative response, @vishalbollu! I really like the way you break down the price by different resources, very useful.

Just to clarify:
1. So what exactly a replica is? What aws resource is it? From what you describe it seems to be an instance for my apps (t3.medium, in your example).
2. Why do we need to use the same instance used for prediction (t3.medium, in your example) for the operator as well? Does it mean that if I want to spin only 1 GPU instance I would need to spin another one?

For the docs, I would explain better what I asked about above (I couldn't find a definition of replica and esk). And give an example of was resources used like above with hyperlinks to their definition and their role.

**Comment by vishalbollu** [comment]
1. I can see how my explanation could have been confusing with my misuse of the word server. A replica is a copy of your application. You are correct that the aws resource associated with replicas EC2. However, multiple replicas can be scheduled on a single EC2 instance depending on the compute requirements of a replica and the compute available on an EC2 instance. For example, if 1 copy of your application such as the Cortex Predictor requires 1 CPU and 1 GB memory and you had an instance with 4 CPU and 4 GB memory available, you would be able to run 4 replicas on that instance.

2. The Cortex operator requires 1 t3.medium instance and is responsible for tasks such as responding to your CLI requests, performing API autoscaling, and other housekeeping processes. The instance allocated for the Cortex operator is always a single t3.medium and is separate from the pool of EC2 instances dedicated to your API. It just so happened that the example used t3.mediums for the APIs. If I wanted to serve models on GPU instances, the operator would still run on a t3.medium, not on one of the GPU instances.

I hope this provides some clarification. Thanks for the docs suggestions, there is definitely room for improvement :)

**Comment by timsoraro** [comment]
Now everything is clear. Thanks a lot!
