### ISSUE TITLE
Cortex gets stuck on 1 stale instance

### ISSUE THREAD

**Issue by timsoraro** [cortexlabs/cortex#1174]
I know the stale replica should automatically be replaced with the requested replica once it's ready. But it seems to take forever (is it because it is trying to have no downtime yet I set the number of max instances to 1?). How can I force it to change?

![Screen Shot 2020-06-27 at 3 47 04 PM](https://user-images.githubusercontent.com/61194445/85922622-8e912d80-b88d-11ea-8daa-9a590fb50979.png)

EDIT: I ended up just killing the API and deploying it again, but thought of letting you know this.

**Comment by deliahu** [comment]
@timsoraro 

> is it because it is trying to have no downtime yet I set the number of max instances to 1?

Yes, that is exactly right! (in combination with the fact that the CPU / GPU / memory compute request for your API was likely too big to be able to fit two replica on a single instance)

> How can I force it to change?

See our documentation [here](https://docs.cortex.dev/troubleshooting/stuck-updating) (this page also has some info describing the behavior that you saw)

**Comment by timsoraro** [comment]
Gotcha, thanks! I miss that info in the docs.

Cortex is really awesome. I've been looking for something like that for so long, and not until I got really frustrated with Algorithmia that I searched for alternatives, found Cortex, and in 1 day set up everything to work in production (:

**Comment by deliahu** [comment]
@timsoraro I'm glad to hear that it's working well for you! I'd love to hear about your use case, and if you have any other suggestions or feature requests; if you're open to chatting feel free to email me at david@cortex.dev

**Comment by timsoraro** [comment]
Sure! Just emailed you (:
