### ISSUE TITLE
How to reuse the port and identity the API by URI

### ISSUE THREAD

**Issue by MrRace** [cortexlabs/cortex#1190]
If I want to use the same port for different API, for example：`http:localhost:8888/uri1` and `http:localhost:8888/uri2`. How should I set in `cortex.yaml` and `predictor.py`, is there any example？

**Comment by dsuess** [comment]
I think it's not possible at the moment with local deployments. Good news is that it's been raised before, see #961

**Comment by deliahu** [comment]
@dsuess yes, that is correct, thank you for linking to #961; I'll go ahead and close this issue given that we have #961 to track this
