### ISSUE TITLE
Can cortex be configured to automatically restart a replica if it crashes?

### ISSUE THREAD

**Issue by timsoraro** [cortexlabs/cortex#1194]
Hi!

Let's say one replica crashes because of some error in the code, can Cortex automatically restart the replica?

**Comment by deliahu** [comment]
Yes, the replica should automatically restart. Have you seen a case where it failed but did not restart?

**Comment by timsoraro** [comment]
I'm sorry, I guess it was because I set the maximum_instances to 1. My bad. I'll report if that happens again when I set it to more than 1!

**Comment by deliahu** [comment]
@timsoraro Even with `max_instances` set to 1, the replica should restart if it fails. Feel free to reach out again if you notice it not restarting!

**Comment by timsoraro** [comment]
I will! (: 👍
