### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by YashRunwal** [cortexlabs/cortex#1195]
Is this not supported for windows? Because when I tried to execute it displayed "Only for Linux and Mac"

**Comment by vishalbollu** [comment]
You are correct, Cortex is not supported for Windows at the moment. The ticket for tracking Windows CLI support can be found here #715.

**Comment by deliahu** [comment]
I'll go ahead and close this issue since we have https://github.com/cortexlabs/cortex/issues/715
