### ISSUE TITLE
Request takes 30% more time. Can this delay be reduced?

### ISSUE THREAD

**Issue by andriy-tsvikla** [cortexlabs/cortex#1200]
v17.1
I have model deployed on virtual machine and model deployed on cortex node.
Model execution takes same time but request to cortex takes 30% more time. ~42ms(virtual machine) vs ~55ms(cortex)
Is there any way to fix it by disabling monitoring etc.?

**Comment by andriy-tsvikla** [comment]
after additional testing from different request source increase was only ~8%

**Comment by deliahu** [comment]
@andriy-tsvikla What exactly is being measured by the timing data? Is it the total time the request takes, as seen by the client? (e.g. is it `time curl http://...`? If so, can you share where the client is running and where the VM is running (if they are different)? Also, are the VM and Cortex in the same AWS region?

**Comment by deliahu** [comment]
update: I see that you just closed this issue, feel free to ignore my previous message if it's been resolved 👍
