### ISSUE TITLE
Bad request is returning 500 status code instead of 400

### ISSUE THREAD

**Issue by MrRace** [cortexlabs/cortex#1208]
1. When post a bad request that should be a json, how can I define the response for the client？ It seems just reply "500 Internal Server Error" now.  When the client post a request that is not  json format, how can I tell the client with the response? 
2.  If I do not set the `-H "Content-Type: application/json"`, but the request data is  standard json format, the payload in the server is empty.  I just print the `payload` in the `predict` :
```
        print("payload type=", type(payload))
        print("payload=", payload)
```
the print result are below:
```
payload type= starlette.datastructures.FormData
payload= FormData([]) # it is empty, why?
```
why the body get by the server is empty?
Thanks a lot!

**Comment by RobertLucian** [comment]
@MrRace thank you a lot for reporting this. Indeed, this doesn't appear to be the right behavior for the webserver:

1. When a post request is made that has a malformed JSON associated with it, a 400 error code should be returned.
1. When the content-type is not set (i.e.`"Content-Type: "`), your `payload` parameter should be a `bytes` object.

Now, when there's no header at all (not just when the content-type is not set), it appears that FastAPI decides that has to be a `starlette.datastructures.FormData` object. Therefore, we're gonna leave it as it is.

**Comment by RobertLucian** [comment]
@MrRace we've created PR #1212 to address this problem.
