### ISSUE TITLE
Allow user to specify a pre-existing API Gateway for the cluster

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1211]
#### Notes

`cluster up` would not create one, and `cluster down` would not delete it (although it may remove any routes it created for that cluster)

**Comment by sladyn98** [comment]
@deliahu I would like to give this a shot, is it open for opening PR's

**Comment by deliahu** [comment]
@sladyn98 Thanks for reaching out!

We are planning on implementing https://github.com/cortexlabs/cortex/issues/1198 in the next week or so. I think it might be good to hold off until that change gets in, since it will lay the groundwork, and will also probably touch most of the places in the codebase that will be modified again for supporting a pre-existing API Gateway.

We actually aren't yet 100% sure we want to support the ability to use a pre-existing API Gateway. I think it could make sense in a world where we also support REST API Gateway (https://github.com/cortexlabs/cortex/issues/1197) (right now we only support HTTP), since there is a lot more configuration that a user might associate with a REST gateway (HTTP is not super configurable beyond routing). We plan on discussing this internally soon, since we have to make sure that the feature is worth the implementation and maintenance cost.

Does that make sense to you? Is there a specific reason that this feature will be useful for you, or that you think this will be useful for others?
