### ISSUE TITLE
Use nvidia-container-toolkit instead of nvidia-docker2 to expose GPUs in Cortex local

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#1223]
#### Description

Cortex local currently relies on setting up a docker runtime with nvidia-docker2 to access gpus. This method is deprecated as of Docker version 19.03. For Docker versions >= 19.03, GPUs should be accessible via `--gpus all` flag after installing nvidia-container-toolkit https://github.com/NVIDIA/nvidia-docker#quickstart.

If it is possible, support both ways of exposing GPUs to Cortex local.

**Comment by dakshvar22** [comment]
Hi, is nvidia-docker2 still supported? I have docker version < 19.03 and nvidia-docker2 install and I would like to leverage GPU without having to upgrade docker. Currently with v0.20 it doesn't seem like GPU is made available inside the service. Can you please clarify?

**Comment by deliahu** [comment]
@dakshvar22 yes, it should fall back on nvidia-docker2 if nvidia-container-toolkit is not found. What is the error message that you see when you try?

**Comment by dakshvar22** [comment]
I don't see any error, but the GPU isn't visible inside the container and
hence not used by the inference API.

**Comment by deliahu** [comment]
@dakshvar22 are you running an example from the cortex repo (if so, which one?), or your own API (if so, which predictor type?). Also, what is the base image you're using for the API container, or are you using the default?

**Comment by dakshvar22** [comment]
I am using my own API which is just a Python Predictor API since my model
is trained in fairseq lib. I am using the default GPU docker image which is
mentioned in the docs for python predictor API.

**Comment by deliahu** [comment]
@dakshvar22 do you mind sharing your `cortex.yaml` file, as well as a simple `Dockerfile` and `predictor.py` which can be used to reproduce it?

For example, the Dockerfile might just show:

```Dockerfile
FROM cortexlabs/python-predictor-gpu-slim:0.20.0-cuda10.1
RUN ... # install your dependencies
```

And your `predictor.py` might just show:

```python
class PythonPredictor:
    def __init__(self, config):
        print(is_gpu_visible())  # replace is_gpu_visible() with the the appropriate function call

    def predict(self, payload):
        return "ok"
```

**Comment by vishalbollu** [comment]
@dakshvar22 It would also be helpful if you can share the output `docker info`. Also can you confirm that you've requested for a GPU in your cortex.yaml?

e.g.
```
- name: myapi
  kind: RealtimeAPI
  predictor:
    ...
  compute:
    gpu: 1
```
