### ISSUE TITLE
Improve credentials transparency for cluster commands

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#1229]
#### Description

Non-cluster (get/deploy/delete/logs/refresh/predict) CLI commands will only use AWS creds from the environment configured by `cortex env configure <env_name>`.

Cortex cluster commands will use AWS credentials based on this priority:
1. Environment variables (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`).
2. AWS config (default credentials `~/.aws/`).
3. Cortex CLI config set via `cortex env configure <env_name>`.
4. Cortex Cluster config - not relevant for your case because you aren't specifying the cluster configuration to the command e.g. `cortex cluster info -c cluster.yaml`.
5. Cortex CLI prompt.

The differences in behaviour between cluster commands and non-cluster commands can be confusing for users. It is also not obvious which credentials are being used by the cluster commands.

The cluster commands can not rely on the environment because the current implementation of the environment requires an operator url for AWS provider.

#### Additional context
- How do other tools that run on top of AWS do their credential management (e.g. serverless)

**Comment by RobertLucian** [comment]
With https://github.com/cortexlabs/cortex/pull/1378 and https://github.com/cortexlabs/cortex/pull/1403 in, the order for all `cortex cluster` commands is:
1. Cortex CLI flags.
1. Cortex CLI cache.
1. Environment variables (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`).
1. AWS config (default credentials `~/.aws/`).
1. Cortex CLI Prompt.
