### ISSUE TITLE
Improve message for OOM error when deploying API

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1233]
#### Description

If an OOM situation is encountered when deploying using the `aws` provider, the logs won't show anything. Here's an example:

```text
using aws environment

fetching logs ...
2020-07-17 14:53:57.307905:cortex:pid-1:INFO:downloading the project code
2020-07-17 14:53:57.463094:cortex:pid-1:INFO:downloading the python serving image
2020-07-17 14:54:00.609957:cortex:pid-22:INFO:loading the predictor from predictor.py
/src/cortex/serve/run.sh: line 88:    22 Killed                  /opt/conda/envs/env/bin/python /src/cortex/serve/start_uvicorn.py
```

The OOM error message is already shown when running `cortex get`:

```bash
env     api     status                  up-to-date   requested   failed   last update   avg request   2XX
aws     api-1   error (out of memory)   0            1           8        25m           -             -
```

In addition to showing up in `cortex get`, there could be a line added to the API's logs. This probably does not merit its own dedicated cron task, but if one is added in the future, it could handle this.

#### Reproducibility

Use the following predictor implementation for a `t3.medium` instance:
```python
import numpy as np

class PythonPredictor:
        def __init__(self, config):
                self.d = np.ones((1000,2000,2000), dtype=np.float64)
        def predict(self, payload):
                return None
```

With the following `cortex.yaml` config:
```yaml
- name: api
  kind: SyncAPI
  predictor:
    type: python
    path: predictor.py
```

#### Notes

Consider adding additional information, such as the amount of memory used at the time of eviction.

**Comment by Papaass** [comment]
To solve this kind of problem, it is necessary to modify the compute section of the cortex.yaml file by increasing the variables cpu and mem.

**Comment by vishalbollu** [comment]
Closing because cortex get shows OOM status and k8s pod events are now exported to cloudwatch.
