### ISSUE TITLE
Image download shown as successful but see error: "No such image: cortexlabs/python-predictor-cpu:0.18.1"

### ISSUE THREAD

**Issue by rcammisola** [cortexlabs/cortex#1236]
#### Version

0.18.1

#### Description

On Mac OS (High Sierra) docker pull silently fails when downloading the python-predictor-cpu image:

```
￮ downloading docker image cortexlabs/python-predictor-cpu:0.18.1 .................................................................... ✓
/Users/rocco.cammisola/Documents/[PROJECT DIR]/cortex.yaml: [API ENDPOINT NAME]: Error response from daemon: No such image: cortexlabs/python-predictor-cpu:0.18.1
```

The output suggests that the download was successful but when I performed `docker pull cortexlabs/python-predictor-cpu:0.18.1` I found out that my docker VM had run out of space.

Performing `docker system prune` (or similar) to clear the VM resolved the issue.

#### Steps to reproduce

1. Set docker VM size on Mac to be smaller than the cortexlabs python predictor image
2. cortex deploy

#### Expected behavior

The download is not marked as successful (tick not shown) and the error about being out of space is reported.

#### Actual behavior

Download marked as successful, no error directly related to not being able to pull the image.

**Comment by vishalbollu** [comment]
Thanks for filing the issue with the reproduction steps and so much detail. We will look into it and try to surface a meaningful error when image download fails.
