### ISSUE TITLE
Perform a complete rollback if one of the update steps fail

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#1250]
#### Description

PR: https://github.com/cortexlabs/cortex/pull/1387/files

There are two steps when updating an API. First the K8s resources are updated, and if that is successful, API gateway is updated. There is a possibility where K8s resources were updated successfully but the API Gateway update failed. If the user were updating the API endpoint in such a scenario, the API would still be considered as live in `cortex get` but it might not be reachable because of the mismatch routes between API Gateway and and the virtual service.

In order to determine whether a deployment of an API is a creation or an update to an existing API, the relevant k8s resources are queried. One solution to recover from partial failure is to do a complete rollback and apply the previous K8s resources and reapply the previous version of API Gateway. 

The error message should contain the status of the rollback.

**Comment by miguelvr** [comment]
@vishalbollu is this still relevant with #1751 ?
