### ISSUE TITLE
Update driver version of EC2 image

### ISSUE THREAD

**Issue by dsuess** [cortexlabs/cortex#1254]
#### Description

The current docker-images use CUDA 10.1, since that seems to be the least common denominator between all the packages used. However, when we tried to run pytorch with CUDA 10.2 (necessary because of pytorch extensions compiled with 10.2), we're getting a runtime error
```
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version ...
```

#### Motivation

Pytorch 1.5 and 1.6 come by default compiled against CUDA 10.2 so it would be nice if the underlying EC2 image's driver would be compatible with CUDA 10.2.

**Comment by deliahu** [comment]
@dsuess do you mind sharing how you approached installing CUDA 10.2? The way I was thinking it could work would be to clone the cortex repo and modify the base cuda image used in the first line of `images/python-predictor-gpu/Dockerfile`. You also might as well re-purpose [this section](https://github.com/cortexlabs/cortex/blob/0.18/images/python-predictor-gpu/Dockerfile#L42-L78) to install whichever packages you need (remove the `test "${SLIM}" = "true"` part as well), or remove the section entirely if you plan on using a `requirements.txt`. You can then run `docker build -f images/python-predictor-gpu/Dockerfile` from the root of the repo to build the image.

I also spoke with @RobertLucian, and we came up with plan where we could build and publish a base image of `python-predictor-gpu-slim` for each CUDA version. I updated https://github.com/cortexlabs/cortex/issues/923 accordingly.
