### ISSUE TITLE
Automated API documentation 

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [cortexlabs/cortex#1318]
#### Description

Having automated API documentation, such as OpenAPI / Swagger. In your functions, you define certain inputs and outputs and this results in a page available on the same endpoint as your actual API, with details what the request should contain. 

#### Motivation

This is a feature that FastApi offers and is something very valuable for cross-discipline teams where the consumers of the API are not working on that api. 

#### Additional context

https://fastapi.tiangolo.com/#interactive-api-docs

**Comment by RobertLucian** [comment]
This looks interesting and we can definitely see its use-case. Thanks for filling in this feature request. We'll have a better look at it.
