### ISSUE TITLE
Provide log filters to cortex logs CLI command

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1326]
#### Description

Provide a `--filter` option to `cortex logs` command to be able to filter out logs. The value that's passed to the `--filter` option can be a string denoting the substring that must be present in a log in order for it to be shown.

Or something like [logging.Logger.addFilter](https://docs.python.org/3/library/logging.html#logging.Logger.addFilter) can be used. But in this case, logs printed with the regular `print` function from within the `predict` method might be missed out.

#### Motivation

As the number of logs increases, being able to filter the logs based on a specific tag/substring becomes more important.

#### Additional context

May increase the priority of this ticket with the addition of #619 and #1252.

**Comment by G-Sheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by deliahu** [comment]
@G-Sheridan Yes, I think this could be a good first issue. There are a few details that have not been scoped out, so I think if someone wanted to contribute this, we would want to have a quick chat about implementation details. But that is certainly doable, so I'll go ahead an add the label. Thanks!
