### ISSUE TITLE
Run outside of aws

### ISSUE THREAD

**Issue by arita37** [cortexlabs/cortex#1330]
This is not clear in the docs,
how to run outside of aws ?

Can disable auto-scale ?

**Comment by deliahu** [comment]
@arita37 Yes, it is possible to run Cortex outside of AWS by using the "local" environment. You would just need to expose the port that your API is running on to make it available to external clients. Here is a guide for how to run on a single AWS node, and the instructions should be fairly similar for other cloud providers: https://docs.cortex.dev/guides/single-node-deployment

As you mentioned, features such as autoscaling and rolling updates are not available when running locally.

**Comment by deliahu** [comment]
Cortex does not yet natively support running on Azure with multiple instances (the steps in the guide I sent above can be used to run on Azure with a single instance). It might be possible to manually set up a load balancer outside of cortex to make it work, but it is not something that we have tried yet.

**Comment by arita37** [comment]
Thanks.
Just checking how the volume is handle :
Per instance:
    1 web server + 1 model running ?

Loading balancing is done by increskng the scale.


While not using docker as a reference node ?

**Comment by deliahu** [comment]
In the local environment, there will be one web server per API endpoint, each running in a different container and on a different port. It is also possible to have multiple models in a single API endpoint, so the user could select which one e.g. with a query parameter (like `http://localhost:8888?model=model1`).

In the AWS environment, each API can have multiple replicas running. Autoscaling will determine how many replicas are running. A replica can be thought of as a single container running a web server. Like with local, it is possible to have multiple models in a single API endpoint, or you can deploy a separate API endpoint for each model.

**Comment by arita37** [comment]
It seems that scaling is done
at AWS instance level :  
   1 Web + 1 backend compute.

Can you change to have :
   Scaling Unit ;
       one docker (instead of one instance).

In the case of Aws, you can keep 1 to 1 mapping.


In case of very big model,
You need also big instance....

**Comment by deliahu** [comment]
I'm not sure if I understand your question, but you can have multiple API containers running on a single instance. If you have a very big model, you will want to choose an instance that is large, and only run a single API container per instance.

In Cortex, we call the API container a "replica" (since it's actually a kubernetes pod which contains a few containers).

**Comment by arita37** [comment]
Ok, not clear how the de-coupling
is done on the code level.

1 model == 1 api entry point ?

**Comment by deliahu** [comment]
Typically 1 model == 1 api entry point, and this is the case in the [tutorial](https://docs.cortex.dev/tutorial). However it is possible to serve multiple models in a single api entry point, see here: https://docs.cortex.dev/guides/multi-model

**Comment by deliahu** [comment]
I'll go ahead and close this issue, feel free to reach out here or on our gitter ([gitter.im/cortexlabs/cortex](https://gitter.im/cortexlabs/cortex)) if you have any more questions
