### ISSUE TITLE
Extract docker container from cortex

### ISSUE THREAD

**Issue by ydennisy** [cortexlabs/cortex#1362]
Is it possible to extract the created docker image from the cortex workflow to deploy outside of AWS?

**Comment by RobertLucian** [comment]
@ydennisy the Cortex Docker images (i.e. `cortexlabs/python-predictor-cpu`) are designed to be used within the context of Cortex and aren't easily adaptable to be run on their own as standalone containers.

You can deploy outside of AWS with Cortex though, albeit with fewer features than on AWS (autoscaling, rolling updates, etc). For that, you'll need to use the local Cortex environment. You can use that to deploy a single-node API on the same machine as where your CLI is installed on. You can follow the instructions in this [guide](https://docs.cortex.dev/guides/single-node-deployment) to deploy one on yours.

Does this answer your question, or are you referring to something else? And on what infrastructure are you hoping to run Cortex?

**Comment by ydennisy** [comment]
Hey @RobertLucian thanks for your reply!

I was hoping to deploy on Cloud Run (GCP), where the input is a docker container, this is why I thought after using the cortex cli locally it would be possible to find the container you guys create to deploy on run.

I have seen the single node guide, what features still available when deploying in this manner?

Out of interest, why are the containers not portable - I thought this what a container was designed for, that it could be run anywhere?

**Comment by RobertLucian** [comment]
@ydennisy I see. Yes, the GCP is a popular request - as a matter of fact, we have a ticket here for it https://github.com/cortexlabs/cortex/issues/114.

With regards to the `local` provider (aka the type of environment used in the single node guide), we try to keep it as close as possible to what the `aws` provider offers. The major features you don't get are the rolling updates, the autoscaling, and the performance monitoring of deployments (i.e. AWS CloudWatch).

We added the support for local deployments with the thought of simplifying the development process - and not necessarily for production-related reasons. That being said, using the `local` provider for production workloads is still totally okay, especially for smaller projects.

> Out of interest, why are the containers not portable - I thought this what a container was designed for, that it could be run anywhere?

What do you mean by portable? If you mean running them standalone, then the answer is that the containers are deeply integrated with AWS and Cortex internals. For example, the container has an internal API which is more complicated than the API that Cortex exposes to the user, it has multiple sidecar containers and daemonsets which must be run alongside it (e.g. to run TensorFlow Serving, expose GPU and Inferentia hardware, track in-flight requests, etc), it uploads logs/metrics to CloudWatch, etc. In addition, the deployment specs which are passed into the serving container are built dynamically when an API is deployed.

I think that from the user's perspective, he/she should only be concerned with the following:
* The API configuration (`cortex.yaml`).
* The predictor implementation (i.e. `predictor.py`).
* Optionally the cluster configuration when the `aws` provider is used (`cluster.yaml`).

Let me know if this makes sense to you.

**Comment by ydennisy** [comment]
@RobertLucian yes it does make sense! Thanks for taking the time to explain.

I think I will give the single node version a try over the weekend and report back.

I have seen the GCP ticket, but looking at the history it keeps getting pushed back.

**Comment by deliahu** [comment]
@ydennisy We've started working on supporting GCP clusters, and we're hoping to have it ready for our v0.23 or v0.24 release.

I'll go ahead and close this issue (since we have https://github.com/cortexlabs/cortex/issues/114)

**Comment by ydennisy** [comment]
Thanks @deliahu
