### ISSUE TITLE
User defined network for local

### ISSUE THREAD

**Issue by BogdanDarius** [cortexlabs/cortex#1379]
#### Description

Right now you can specify the port when you run cortex locally.
It would be nice to allow a user defined network for the docker container.
```yaml
networking:
  network: my-custom-net | bridge
```
#### Motivation

I was setting up an API Gateway (Kong) in front of cortex.
In order to forward the request cortex container must be on the same network as kong.

**Comment by vishalbollu** [comment]
@BogdanDarius thanks for filing the issue. I did quick scan of the [docker docs](https://docs.docker.com/engine/reference/commandline/network_connect/) and I was wondering if `docker connect` could be used in your use case to add the Cortex API container to your user defined network.
