### ISSUE TITLE
Why cant't I install Cortex on Windows?

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1418]
I've downloaded and installed Docker on my Windows. When I try to install cortex using command provided in the installation instructions: **bash -c "$(curl -sS https://raw.githubusercontent.com/cortexlabs/cortex/0.20/get-cli.sh)"**
I get: **/bin/bash: #!/bin/bash: No such file or directory** error. Does anyone know how to fix this?

**Comment by imagine3D-ai** [comment]
Solved by saving get-cli.sh to Desktop and then running it using bash

**Comment by RobertLucian** [comment]
@imagine3D-ai to make things clear, we don't support the Cortex CLI on Windows yet - I think the only option is to use the Linux Subsystem on Windows, which is what I think you did.

As for why it didn't work for you, maybe [this can help](https://unix.stackexchange.com/questions/27054/bin-bash-no-such-file-or-directory) explain the cause. Also, running `which bash` in your terminal will tell you where `bash` is installed.
