### ISSUE TITLE
Unable to connect to Docker daemon WINDOWS

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1419]
I've installed Stable Docker Desktop for WINDOWS 10. I tried running:

```
docker run hello-world
    Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.
```

So it appears that it can connect to Docker daemon. However when I run my own command:

```
C:\Users\cortex>bash
DESKTOP-2GHN95P:/tmp/docker-desktop-root/mnt/host/c/Users/cortex/# cortex deploy
```

I get following error:

```
error: unable to connect to the Docker daemon

please confirm Docker is running, or if Docker is not installed, install it by following the instructions for your operating system: https://docs.docker.com/install
```

I'm new to Docker and I can't figure out this problem. Anyone has any ideas?

**Comment by deliahu** [comment]
@imagine3D-ai we don't yet officially support running on Windows. That said, it might be possible by using the Windows Subsystem for Linux. Is this the approach you are trying?

Also, I noticed that first you ran `bash`, and then you ran `cortex deploy`. If you run `bash` and then run `docker run hello-world` does docker work?

**Comment by imagine3D-ai** [comment]
> @imagine3D-ai we don't yet officially support running on Windows. That said, it might be possible by using the Windows Subsystem for Linux. Is this the approach you are trying?
> 
> Also, I noticed that first you ran `bash`, and then you ran `cortex deploy`. If you run `bash` and then run `docker run hello-world` does docker work?

Actually not.. 
`bash: docker: command not found`

So it's not running from bash for some reason

**Comment by RobertLucian** [comment]
@imagine3D-ai that's because you don't have `docker` installed on your Linux Subsystem. The Cortex CLI requires Docker to be installed. I think that for Windows machines running with the Linux Subsystem, you can follow [these instructions](https://medium.com/faun/docker-running-seamlessly-in-windows-subsystem-linux-6ef8412377aa) to get it installed on yours. I haven't tried this though.

**Comment by imagine3D-ai** [comment]
Solved by installing Ubuntu for Windows and running commands from there

**Comment by deliahu** [comment]
@imagine3D-ai just out of curiosity, were you able to get this working, and if so, was it by installing docker in your linux subsystem?

**Comment by imagine3D-ai** [comment]
> @imagine3D-ai just out of curiosity, were you able to get this working, and if so, was it by installing docker in your linux subsystem?

I've installed Ubuntu on my machine and installed docker there.

**Comment by RobertLucian** [comment]
@imagine3D-ai thanks for letting us know. We also have a ticket to support the CLI to run on Windows https://github.com/cortexlabs/cortex/issues/715, so this is on our radar.
