### ISSUE TITLE
Cluster creation fails at creating api gateway vpc link

### ISSUE THREAD

**Issue by BogdanDarius** [cortexlabs/cortex#1433]
#### Version

cli version: 0.20.0

#### Description

Cluster creation fails at **creating api gateway vpc link integration** step 
```python
Traceback (most recent call last):
  File "create_gateway_integration.py", line 79, in <module>
    create_gateway_intregration(api_id, vpc_link_id)
  File "create_gateway_integration.py", line 63, in create_gateway_intregration
    listener_arn = get_listener_arn(elb_arn, client_elb)
  File "create_gateway_integration.py", line 55, in get_listener_arn
    raise Exception("Could not find ELB port 80 listener")
Exception: Could not find ELB port 80 listener
```
#### Configuration
```yaml
cluster_name: test-api
region: eu-central-1
bucket: test-api-91koq2px41
availability_zones: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
instance_type: m3.medium
min_instances: 1
max_instances: 10
instance_volume_size: 30
instance_volume_type: gp2
subnet_visibility: public
nat_gateway: none
api_load_balancer_scheme: internal
operator_load_balancer_scheme: internet-facing
api_gateway: public
log_group: test-api
spot: false
```

#### Steps to reproduce

``` 
cortex cluster up --config cluster.yaml 
```

#### Expected behavior

Cluster creation

#### Actual behavior

Cluster creation fails 

#### Screenshots

![error](https://user-images.githubusercontent.com/25986436/95667520-eec38b00-0b6f-11eb-89e7-26b3a2e3e747.png)

**Comment by deliahu** [comment]
@BogdanDarius Thank you for providing all of the information, that is very helpful!

I have been able to reproduce this, and I don't know yet exactly what is causing it, but I will keep you posted

**Comment by deliahu** [comment]
@BogdanDarius I don't yet know for sure what the issue is, however I wanted to update you that I was able to spin up a cluster by changing the instance type and leaving the rest of the configuration the same.

Are you able to try again with a different instance type? I tried with m5.large, but if you want a smaller one, I expect that the t3 or t3a series will work.

**Comment by BogdanDarius** [comment]
@deliahu You are right, everything works with t3 instance.
Maybe add some notice/documentation that it doesnt work with m3 instance right now?

**Comment by deliahu** [comment]
@BogdanDarius I'm glad to hear that it's working for you now.

I've created https://github.com/cortexlabs/cortex/pull/1436 so that in the future, choosing an instance type that is not supported by AWS NLB's target groups will be blocked.

Thanks for bringing this to our attention!
