### ISSUE TITLE
Error response from daemon: invalid mount config for type "bind" 

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1434]
I want to try deploying iris-classifier from Cortex examples folder to check that my Cortex is working, but I'm getting this error:

```
~/cortex/examples/sklearn/iris-classifier$ cortex deploy

cortex.yaml: iris-classifier (RealtimeAPI): Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/user/cortex/examples/sklearn/iris-classifier

note: deploying an API locally from within a docker container is not supported (although deploying to AWS from within a container is supported)

```

What should I do to fix this?

**Comment by deliahu** [comment]
@imagine3D-ai can you describe your setup, for example, which operating system you're on, how you are running the cortex CLI, and how you have installed docker so that the corex cli can access it?

**Comment by imagine3D-ai** [comment]
> @imagine3D-ai can you describe your setup, for example, which operating system you're on, how you are running the cortex CLI, and how you have installed docker so that the corex cli can access it?

Yes of course. I'm running this on Ubuntu for Windows 10. I've installed cortex cli using this command (found in cortex installation guide) in Ubuntu :
`bash -c "$(curl -sS https://raw.githubusercontent.com/cortexlabs/cortex/0.20/get-cli.sh)"`

**Comment by imagine3D-ai** [comment]
> @imagine3D-ai can you describe your setup, for example, which operating system you're on, how you are running the cortex CLI, and how you have installed docker so that the corex cli can access it?

and I've installed Docker just by using the official installer: https://hub.docker.com/editions/community/docker-ce-desktop-windows/

**Comment by deliahu** [comment]
My best guess is that the root of the issue is that the docker daemon is running in the windows environment, but the cortex CLI is running in ubuntu. Therefore, the docker daemon does not have access to the ubuntu file system (which the cortex CLI is operating on), since it's running in windows.

If this is the case, there are two possibilities to resolve this:

1. Install docker in the ubuntu environment instead of in windows
2. Use cortex to deploy to AWS instead of deploying locally

We are hoping to support windows natively (https://github.com/cortexlabs/cortex/issues/715), so you wouldn't have to run in ubuntu, but we don't yet know exactly when that will be ready.

In the meantime, would one of the above options work for you?

**Comment by mutal** [comment]
> My best guess is that the root of the issue is that the docker daemon is running in the windows environment, but the cortex CLI is running in ubuntu. Therefore, the docker daemon does not have access to the ubuntu file system (which the cortex CLI is operating on), since it's running in windows.
> 
> If this is the case, there are two possibilities to resolve this:
> 
> 1. Install docker in the ubuntu environment instead of in windows
> 2. Use cortex to deploy to AWS instead of deploying locally
> 
> We are hoping to support windows natively (#715), so you wouldn't have to run in ubuntu, but we don't yet know exactly when that will be ready.
> 
> In the meantime, would one of the above options work for you?

Where can I find tutorials on deploying cortex to AWS?

**Comment by imagine3D-ai** [comment]
I’ll try deploying to AWS, where can I find instructions to do that?

**Comment by RobertLucian** [comment]
@imagine3D-ai to deploy to AWS (using Cortex), you'll have to first spin up a cluster and then deploy to it your API.

To spin up a cluster, you can either use the CLI's prompt for the `cortex cluster up` command to feed in your cluster's specs (name, instance type, region, etc) or you can provide your own `cluster.yaml` config that offers more granular control over your cluster's specs. Here's the [template](https://docs.cortex.dev/cluster-management/config) for the `cluster.yaml` config. And [this is](https://docs.cortex.dev/miscellaneous/cli#cluster-up) the spec for the `cortex cluster up` command. If you want to provide the `-e` option to the command to give a specific name to your environment, you might also want to go through the [environments](https://docs.cortex.dev/miscellaneous/environments) docs.

Once the cluster is up, you can then just go to an example and deploy it to the AWS cluster - when deploying to AWS, you'll need to specify the environment to use (the default one for clusters is the `aws` one, so you'll have to specify that).

We also have a [simple tutorial](https://docs.cortex.dev/v/0.20/deployments/realtime-api/text-generator#deploy-your-model-to-aws) involving the iris classifier API here that shows you how to deploy to AWS.
