### ISSUE TITLE
Running AWS cluster costs

### ISSUE THREAD

**Issue by mutal** [cortexlabs/cortex#1442]
I'm considering launching AWS cluster with few instances and keep the costs as low as possible. Before launching the cluster, cortex gave this info:

```
aws resource                              cost per hour
1 eks cluster                             $0.10
1 - 5 t3.medium instances for your apis   $0.0416 each
1 - 5 50gb ebs volumes for your apis      $0.007 each
1 t3.medium instance for the operator     $0.0416
1 20gb ebs volume for the operator        $0.003
2 network load balancers                  $0.0225 each

your cluster will cost $0.24 - $0.43 per hour based on cluster size
```

So, as I understand the fixed cost of running the cluster is a minimum of 0.24$/hour. I'm wondering if Cortex can shutdown the cluster when no instances are being used, to avoid unneccesary expenses or are there any other work-arounds to keep the costs down?

**Comment by deliahu** [comment]
Yes, $0.24/hour will be the cost of the cluster if there is a single instance running (your minimum). If 5 instances are running (your maximum), it will be $0.43/hour.

There is not a way to shut down instances based on request load. There are a few things that you can do to help reduce costs:

* If you delete an API with `cortex delete <api name>`, then it will allow the API instances to scale down. You could set min instances to 0, and then the fixed cost of the cluster if no APIs are deployed should be ~$0.20 per hour.
* If you have APIs running which cannot be deleted, you can consider using [spot instances](https://docs.cortex.dev/cluster-management/spot-instances). This will reduce the cost of running your API instances.
* If you don't have a high request load and have multiple APIs running, you can "fit" multiple APIs on a single instance by adjusting the compute request for each API. It is also possible to serve multiple models from a single API if desired (here is [an example](https://github.com/cortexlabs/cortex/blob/master/examples/onnx/multi-model-classifier)).

In any case, there is not currently a way to reduce the fixed cost of the cluster below ~$0.20/hour, without spinning down the cluster via `cortex cluster down`.
