### ISSUE TITLE
Is there a way to select between two models to be deployed to a single cluster?

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1443]
Let's say I have two models which need to be deployed when requested. Is there a way to deploy few different models without creating dedicated cluster for each? I'm thinking something like this:

```
cortex cluster up
cortex deploy mymodel1 --env aws
cortex deploy mymodel2 --env aws
```
or does each model need it's own cluster?

**Comment by deliahu** [comment]
@imagine3D-ai yes you can deploy multiple APIs in a single cluster. There are three options:

1. You can have multiple APIs in a single `cortex.yaml` file, like in [this example](https://github.com/cortexlabs/cortex/blob/master/examples/traffic-splitter/cortex.yaml) (ignore the API of `kind: TrafficSplitter` if that is not relevant to you)
1. You can have two separate files, e.g. `api1.yaml` and `api2.yaml`, and then use `cortex deploy api1.yaml --env aws` and `cortex deploy api2.yaml --env aws`
1. If your models don't share dependencies, it might be cleaner to have two directories, each with a single `cortex.yaml` file (e.g. `model1/cortex.yaml` and `model2/cortex.yaml`. Then you can `cd` into each directory and deploy the API with `cortex deploy --env aws`, or from the parent directory you can use `cortex deploy model1/cortex.yaml --env aws` and `cortex deploy model2/cortex.yaml --env aws`

**Comment by deliahu** [comment]
@imagine3D-ai I'll go ahead and close this issue, feel free to reach out if you have additional questions
