### ISSUE TITLE
Behaviour for Spot instances

### ISSUE THREAD

**Issue by dakshvar22** [cortexlabs/cortex#1447]
Hi,

Since spot instances can be terminated arbitrarily by AWS. I have 2 questions related to them - 

1. What happens to in-flight requests which are let's say in processing, i.e. - The request was passed from the queue to one of the replica and the replica was in the middle of processing it when the instance terminated. Are those requests resent to other live replicas or do they result in 503 errors?
2. AWS pages mention that instances like g4dn.xlarge have a 20% interruption rate. From that perspective, in your experiences, are g4dn.xlarge the best spot instances to use in that case? Is the interruption rate lower for maybe inferentia instances since AWS markets them really for inferencing?

**Comment by RobertLucian** [comment]
@dakshvar22 here are the answers:

1. In-flight requests that are being processed will hang indefinitely and in-flight requests that are in queue will return 503 errors, but not necessarily immediately. Unfortunately, they are not being redirected to other replicas residing on other instances. The remedy to this is to implement retries and timeouts for your application.
1. I think 20% is still okay as long as there are enough spare instances in your region(s). When selecting the spot instance type, there are a couple of criteria: the region, the interruption rate, the cost savings, and the available resources on that instance type. AWS has an advisor for that [here](https://aws.amazon.com/ec2/spot/instance-advisor/). You can use this advisor to judge which instances (`inf1.*`, `g4dn.*`) make more sense (economically, performance-wise, etc) in the region(s) you are considering.

Does this answer your question? Would you much prefer having the requests re-routed/re-tried automatically?

**Comment by dakshvar22** [comment]
@RobertLucian Thanks a lot for the answers. I would definitely prefer having the requests re-routed automatically, or atleast making that option configurable.

**Comment by RobertLucian** [comment]
@dakshvar22 got it. I'll close this ticket for now as we already have #927 where we can track this.
