### ISSUE TITLE
REALTIME API ERROR BUT EVERYTHING WORKS IN COLAB

### ISSUE THREAD

**Issue by da-source** [cortexlabs/cortex#1458]
I'm having trouble implementing my predictor for cortex.
I've succesfully created a cluster and wanted to deploy my Realtime API but I've got this message:

```
$ cortex get                                                                                             10:28:01am CEST

env   realtime api   status   up-to-date   stale   requested   failed   last update   avg request   2XX
aws   gpt2           error    0            1       1           1        4m            -           
```  -


```

My predictor implementation, that I've made in Colab seemed to work fine. 

```
import subprocess
import os
import boto3
import sys

class PythonPredictor:
    def __init__(self, config):
        s3 = boto3.client('s3', aws_access_key_id='mykey',
        aws_secret_access_key='secretkey')
        s3.download_file(config['bucket'], config['key'], "./mymodel.bin")
        print('done')

    def predict(self):
      !chmod +rx ./mymodel
      command = ['./mymodel','-m', 'M', '-l', '20', 'g', 'hi']
      process = subprocess.Popen(command, stdout=subprocess.PIPE, universal_newlines=True)
      while True:
          output = process.stdout.readline()
          if output == '' and process.poll() is not None:
              break
          if output:
              print(output.strip())
      rc = process.poll()
      return rc
```

It successfully downloads mymodel.bin and instantiates PythonPredictor class:

```
p = PythonPredictor(config={'bucket':'mybucket', 'key':'mymodel.bin'})
done

```

and model output when I call predict() is as expected:
```
p.predict()
expected output
```

So everything seems to be working in colab but Cortex is giving me ERROR status.

My project folder is organized like this:
```
--myfolder
---predictor.py
---cortex.yaml
---mymodel
```

Here is predictor.py (It's the same thing as in Colab version above):

```
import subprocess
import os
import boto3
import sys

class PythonPredictor:
    def __init__(self, config):
        s3 = boto3.client('s3', aws_access_key_id='mykey',
        aws_secret_access_key='secretkey')
        s3.download_file(config['bucket'], config['key'], "./mymodel.bin")
        print('done')

    def predict(self):
      !chmod +rx ./mymodel
      command = ['./mymodel','-m', 'M', '-l', '20', 'g', 'hi']
      process = subprocess.Popen(command, stdout=subprocess.PIPE, universal_newlines=True)
      while True:
          output = process.stdout.readline()
          if output == '' and process.poll() is not None:
              break
          if output:
              print(output.strip())
      rc = process.poll()
      return rc
```

And here is cortex.yaml:

```
- name: gpt2
  kind: RealtimeAPI
  predictor:
    type: python
    path: predictor.py
    config:
      bucket: 'mybucket'
      key: 'mymodel.bin'
  compute:
    cpu: 1

```

Why is everything working in Colab, but not in Cortex?

**Comment by vishalbollu** [comment]
You can use the command `cortex logs <API_NAME>` to print logs for your API which could help you debug the errors you are running into.

As for why your Predictor is working in Colab and not in Cortex, Jupyter notebooks and Colabs support convenience features that are not native to Python such as being able to run bash commands with  `!<bash command>`. 

When you run `cortex deploy`, Cortex runs your predictor code in a vanilla Python runtime (python 3.6.9 to be precise) and therefore does not support additional convenience features provided by Jupyter notebooks and Colab.

You can write `!chmod +rx ./mymodel` in python. For example:
```python
import subprocess
import os
import boto3
import sys
import stat

class PythonPredictor:
    def __init__(self, config):
        s3 = boto3.client('s3', aws_access_key_id='mykey',
        aws_secret_access_key='secretkey')
        s3.download_file(config['bucket'], config['key'], "./mymodel.bin")
        st = os.stat('./mymodel')
        os.chmod('./mymodel', st.st_mode | stat.S_IEXEC ) # this should be the equivalent to chmod +x ./mymodel and make your model.bin executable
        print("done")

    def predict(self):
        command = ['./mymodel','-m', 'M', '-l', '20', 'g', 'hi']
        process = subprocess.Popen(command, stdout=subprocess.PIPE, universal_newlines=True)
        while True:
            output = process.stdout.readline()
            if output == '' and process.poll() is not None:
                break
            if output:
                print(output.strip())
        rc = process.poll()
        return rc
```

The code above should work in your Colab and in a Python-only runtime such as Cortex.

**Comment by da-source** [comment]
> You can use the command `cortex logs <API_NAME>` to print logs for your API which could help you debug the errors you are running into.
> 
> As for why your Predictor is working in Colab and not in Cortex, Jupyter notebooks and Colabs support convenience features that are not native to Python such as being able to run bash commands with `!<bash command>`.
> 
> When you run `cortex deploy`, Cortex runs your predictor code in a vanilla Python runtime (python 3.6.9 to be precise) and therefore does not support additional convenience features provided by Jupyter notebooks and Colab.
> 
> You can write `!chmod +rx ./mymodel` in python. For example:
> 
> ```python
> import subprocess
> import os
> import boto3
> import sys
> import stat
> 
> class PythonPredictor:
>     def __init__(self, config):
>         s3 = boto3.client('s3', aws_access_key_id='mykey',
>         aws_secret_access_key='secretkey')
>         s3.download_file(config['bucket'], config['key'], "./mymodel.bin")
>         st = os.stat('./mymodel')
>         os.chmod('./mymodel', st.st_mode | stat.S_IEXEC ) # this should be the equivalent to chmod +x ./mymodel and make your model.bin executable
>         print("done")
> 
>     def predict(self):
>         command = ['./mymodel','-m', 'M', '-l', '20', 'g', 'hi']
>         process = subprocess.Popen(command, stdout=subprocess.PIPE, universal_newlines=True)
>         while True:
>             output = process.stdout.readline()
>             if output == '' and process.poll() is not None:
>                 break
>             if output:
>                 print(output.strip())
>         rc = process.poll()
>         return rc
> ```
> 
> The code above should work in your Colab and in a Python-only runtime such as Cortex.

Thanks a lot, that solved it!
But now I'm getting `no healthy upstream` error when I try to access and get output from my endpoint URL. Since my code doesn't need a payload I just did:
`curl https://myendpoint/mymodel`
`no healthy upstream`

API is live and up-to-date though. What can be causing this message?

**Comment by RobertLucian** [comment]
@da-source to make it clear, `no healthy upstream` is returned when no payload is sent to the server.

At the very least, your command has to look like this:
```bash
curl https://s8u99tpqa2.execute-api.us-west-2.amazonaws.com/iris-classifier -X POST -H "Content-Type: application/json" -d '{}'
```
where `https://s8u99tpqa2.execute-api.us-west-2.amazonaws.com/iris-classifier` is the API's endpoint.

When running `cortex get <api-name>`, you will be encountered with a curl example for your specific API deployment. You can copy-paste it and then provide a `sample.json` to it to make a prediction.

**Comment by imagine3D-ai** [comment]
> @da-source to make it clear, `no healthy upstream` is returned when no payload is sent to the server.
> 
> At the very least, your command has to look like this:
> 
> ```shell
> curl https://s8u99tpqa2.execute-api.us-west-2.amazonaws.com/iris-classifier -X POST -H "Content-Type: application/json" -d '{}'
> ```
> 
> where `https://s8u99tpqa2.execute-api.us-west-2.amazonaws.com/iris-classifier` is the API's endpoint.
> 
> When running `cortex get <api-name>`, you will be encountered with a curl example for your specific API deployment. You can copy-paste it and then provide a `sample.json` to it to make a prediction.

What if my api doesn’t need a payload?

**Comment by RobertLucian** [comment]
@imagine3D-ai you still need to add a payload - the minimum you have to add to your payload if the content type is set to JSON is `{}`. Here is a [guide](https://docs.cortex.dev/deployments/realtime-api/predictors#api-requests) to walk you through all content types supported by Cortex.

**Comment by RobertLucian** [comment]
@imagine3D-ai a correction on my part. We've tested the Cortex, and it actually looks like payload-less requests work. It's just that when `curl`ing, you need to have this format: `curl <api-endpoint> -X POST)`.

Apologies for the inaccuracy.

**Comment by imagine3D-ai** [comment]
> @imagine3D-ai a correction on my part. We've tested the Cortex, and it actually looks like payload-less requests work. It's just that when `curl`ing, you need to have this format: `curl <api-endpoint> -X POST)`.
> 
> Apologies for the inaccuracy.

Thanks for looking into it! But now I'm getting `upstream connect error or disconnect/reset before headers. reset reason: connection termination` followed by `no healthy upstream`:

```
curl <api-endpoint> -X POST
upstream connect error or disconnect/reset before headers. reset reason: connection termination
curl <api-endpoint> -X POST
no healthy upstream
```

**Comment by imagine3D-ai** [comment]
> > @imagine3D-ai a correction on my part. We've tested the Cortex, and it actually looks like payload-less requests work. It's just that when `curl`ing, you need to have this format: `curl <api-endpoint> -X POST)`.
> > Apologies for the inaccuracy.
> 
> Thanks for looking into it! But now I'm getting `upstream connect error or disconnect/reset before headers. reset reason: connection termination` followed by `no healthy upstream`:
> 
> ```
> curl <api-endpoint> -X POST
> upstream connect error or disconnect/reset before headers. reset reason: connection termination
> curl <api-endpoint> -X POST
> no healthy upstream
> ```

Why could that be?
