### ISSUE TITLE
AWS EC2 instances keep launching

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1463]
I've deployed a cluster using `cortex cluster up` and even after shutting it down, 1 EC2 instance keeps coming back. I tried terminating it but it restarts a few minutes later, and I'm being billed this whole time. How can I shut this instance down for good?

**Comment by imagine3D-ai** [comment]
> I've deployed a cluster using `cortex cluster up` and even after shutting it down, 1 EC2 instance keeps coming back. I tried terminating it but it restarts a few minutes later, and I'm being billed this whole time. How can I shut this instance down for good?

I try to select Environments in elastic beanstalk but it keeps throwing me back to the welcome page, so I cant open it:https://console.aws.amazon.com/elasticbeanstalk/home?region=us-east-1#/welcome

**Comment by deliahu** [comment]
@imagine3D-ai If you go to the Cloud Formation dashboard in the AWS console (e.g. for us-west-2 it would be: https://console.aws.amazon.com/cloudformation/home?region=us-west-2), do you see an stacks that are associated with cortex? If so, delete them one at a time by selecting a stack and then clicking "Delete" at the top.

Please let us know if that doesn't fix it.

**Comment by imagine3D-ai** [comment]
Turns out the problem was a Spot Instance Request that kept running. I
fixed it by going to Spot Instances and terminating the request from there.
