### ISSUE TITLE
Issue of mkdir while executing make cluster-up

### ISSUE THREAD

**Issue by AkashDharani** [cortexlabs/cortex#1465]
would you like to continue? (y/n): y

￮ using existing s3 bucket: cortex-c385ab4027 ✓
￮ using existing cloudwatch log group: cortex ✓
￮ using existing cloudwatch dashboard: cortex ✓
￮ creating api gateway: cortex ✓
BusyBox v1.31.1 () multi-call binary.

Usage: mkdir [OPTIONS] DIRECTORY...

Create DIRECTORY

        -m MODE Mode
        -p      No error if exists; make parent directories as needed

**Comment by RobertLucian** [comment]
@AkashDharani I see you solved this? What was the issue?

**Comment by AkashDharani** [comment]
@RobertLucian I resolved this issue by upgrading `cortex-dev` from 0.19 to 0.20.
