### ISSUE TITLE
Support additional volume mounts when deploying locally

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1499]
#### Motivation

Users may wish to save files to locations other than their project directory

**Comment by tall-josh** [comment]
Yes please!!!

**Comment by deliahu** [comment]
Until this is added, one workaround is to run a cron job or filesystem monitor on your host which checks for new files in the cortex project directory, and moves them to another location.

**Comment by amiralikaboli** [comment]
Until this is added, Another way is to create a directory in `/mnt/project` and save files in it.
