### ISSUE TITLE
CORS on local deployment

### ISSUE THREAD

**Issue by miggymigz** [cortexlabs/cortex#1507]
Would it be possible to manually add the allowed hosts when deploying locally?

**Comment by RobertLucian** [comment]
There's currently no user-configurable option to modify the allowed hosts (for CORS) when using Cortex.

That being said, the part of the code that would have to be changed is:
https://github.com/cortexlabs/cortex/blob/06f6d7dd2f05d0119a35a23b22b1fa2af1019195/pkg/workloads/cortex/serve/serve.py#L56-L59
At the time of speaking, you'd need to re-build your predictor image, then push it to your registry (Docker Hub most likely), and then specify the newly uploaded image using the `predictor.image` field in your [`cortex.yaml`](https://docs.cortex.dev/deployments/realtime-api/api-configuration) API spec. The docs on how to set up your environment are found [here](https://docs.cortex.dev/contributing/development).

Let us know if you have any other questions/uncertainties.

**Comment by deliahu** [comment]
@miggymigz I wanted to follow up on this, were you able to get things working as you expected? If not, we can try to reproduce the issue. Are you accessing your APIs locally (e.g. via `http://localhost:8888`), or via the internet (i.e. you are running Cortex locally on a cloud instance)?

**Comment by miggymigz** [comment]
@deliahu Hi. I tried doing what RobertLucian suggested but it was too much work for me. And yes, the goal is to run cortex on several cloud instances (huawei cloud, to be specific) with load balancing. 

We do this since we want to prepare for a LAN deployment (the user of our models is a hospital and they don't want to expose it to the public internet).

Also, the CORS is needed since we access the API with a frontend app running on a different port.

**Comment by deliahu** [comment]
@miggymigz Do you mind sharing the message from the CORS error you're getting, as well as your browser type and version, so I can try to reproduce it?

**Comment by miggymigz** [comment]
@deliahu I'm sorry but I can't reproduce the error now since we changed our backend to fastAPI instead (for easier CORS configuration).

**Comment by deliahu** [comment]
@miggymigz thanks for following up. I'll go ahead and mark this as closed for the time being, feel free to reach out if you run into it again!
