### ISSUE TITLE
How to install Node.js on EC2 instance using Cortex

### ISSUE THREAD

**Issue by da-source** [cortexlabs/cortex#1511]
Is there a way to auto-install Node.js on the instances that Cortex launches?

**Comment by deliahu** [comment]
@da-source It is possible to install Node.js on the API replicas by following these instructions: https://docs.cortex.dev/advanced/system-packages

What is your motivation for installing Node.js? I'm just asking in case there is an alternate solution that would be better for your use case, or if there is a feature that we should consider supporting.

**Comment by da-source** [comment]
> @da-source It is possible to install Node.js on the API replicas by following these instructions: https://docs.cortex.dev/advanced/system-packages
> 
> What is your motivation for installing Node.js? I'm just asking in case there is an alternate solution that would be better for your use case, or if there is a feature that we should consider supporting.

I was looking into creating a websocket on an instance and then streaming the output to a website
