### ISSUE TITLE
Start script getting killed

### ISSUE THREAD

**Issue by krrishdholakia** [cortexlabs/cortex#1518]
Hi, i'm running cortex deploy. Upon checking the cortex logs, i can see:

`/src/cortex/serve/run.sh: line 89:    33 Killed                  /opt/conda/envs/env/bin/python /src/cortex/serve/start.py`

How do i go about debugging this ? i'm not sure what to look for in the start.py

# Context on where it's breaking

`self.model = GPT2LMHeadModel.from_pretrained("./Model/")`

this works when i run it on a jupyter notebook

**Comment by RobertLucian** [comment]
Closing this once, since @deliahu already responded on this matter on Gitter. For clarity, this is caused by an OOM - the instance needs more memory in this case.
