### ISSUE TITLE
Use NGINX to monitor the traffic to the API replica

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1524]
#### Description

Track performance-related metrics (avg request latency, in-flight requests, number of 1xx/2xx/3xx/4xx/5xx errors, etc) using NGINX.

#### Motivation

Cleaner code. Reducing technical debt.

#### Additional context

https://www.datadoghq.com/blog/how-to-monitor-nginx/
https://www.datadoghq.com/blog/how-to-collect-nginx-metrics/
https://www.keycdn.com/support/nginx-status

**Comment by deliahu** [comment]
(duplicate of #841)
