### ISSUE TITLE
Objects in s3

### ISSUE THREAD

**Issue by mrmassis** [cortexlabs/cortex#1531]
I would like to reduce the number of objects in S3. My question is: what parameters could I configure so that the number of objects in S3 would decrease? Would the size of the chunk influence?
Thanks in advance

**Comment by vishalbollu** [comment]
Could you specify the Cortex created S3 folders in which you would like to reduce the number of objects?

Also is it possible that you meant to file this issue in https://github.com/cortexproject/cortex? This GitHub repo is for Cortex, an open source platform for deploying machine learning models to production.

**Comment by mrmassis** [comment]
Sorry by my mistake!
