### ISSUE TITLE
AWS EKS billing much larger than EC2

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1542]
I've been experimenting a little deploying clusters with Cortex this week. When I checked my AWS billing I was surprised to see that my bill was:

```
EKS: 6.56$
EC2: 0.24$
```

I didn't keep clusters running too long and spun them down as soon I was done with the experiments and so my EC2 instance bill is low as expected. But why am I being charged so much for EKS? Do I get charged everytime I spin up the cluster? When I launch cluster using cortex it says that it will cost aroung $0.25/hour (depending on number of instances). In total this week my intances have been up only around 1 hour (since the small EC2 bill). How can I lower/avoid EKS costs?

**Comment by deliahu** [comment]
@imagine3D-ai Can you confirm that there are no EKS clusters running right now, in any regions that you may have used? You can check this in your AWS console: https://console.aws.amazon.com/eks/home

If there aren't any still running (assuming that you don't have any Cortex clusters running at the moment), then I'm not sure what would cause this.

**Comment by imagine3D-ai** [comment]
There was one cluster left running indeed.

**Comment by deliahu** [comment]
@imagine3D-ai were you able to spin down that cluster? If you run into any trouble, we just added this guide on our master branch (which should be released this week): https://docs.cortex.dev/v/master/troubleshooting/cluster-down

**Comment by imagine3D-ai** [comment]
> @imagine3D-ai were you able to spin down that cluster? If you run into any trouble, we just added this guide on our master branch (which should be released this week): https://docs.cortex.dev/v/master/troubleshooting/cluster-down

yes, I’ve closed it.
