### ISSUE TITLE
How many APIs can be deployed to a single cluster?

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1548]
Is there a limit on how many models/APIs that can be served by one cluster?

**Comment by RobertLucian** [comment]
Theoretically, there's no limit to this, as long as the `max_instances` field is updated to a higher value. And there's no soft limit applied to the `max_instances` field in your [`cluster.yaml`](https://docs.cortex.dev/cluster-management/config) config.
