### ISSUE TITLE
Parsing bytes payloads

### ISSUE THREAD

**Issue by DragonDuck** [cortexlabs/cortex#1550]
Hello!

I want to deploy a machine learning service that performs image analysis on an image passed to the API. However, I'm struggling with parsing a bytes payload. My program cannot properly interpret the bytes as an image and It appears that the bytes being passed to the API are incomplete. I am invoking my API as follows:

```
curl http://localhost:8890 -X POST -H "Content-Type: application/octet-stream" -d @input_image.jpg
```

For the sake of this question, `predictor.py` has the following structure:

```
import os
from PIL import Image


class PythonPredictor:
    def __init__(self, config):
        pass

    def predict(self, payload):
        with open("temp_image.jpg", "wb") as f:
            f.write(payload)

        try:
            img = Image.open("temp_image.jpg")
            output = img.size
        except Exception as e:
            output = "Exception: " + str(e)

        return output
```

However, the image isn't being loaded and the API returns the exception string "Exception: cannot identify image file 'temp_image.jpg'".

Further inspection shows that the file written by the API is much smaller than the actual image file. The original image file `input_image.jpg` is 9792 bytes large but `temp_image.jpg` is only 2773 bytes large, which explains why it's not being recognized as an image file.

Did I make a mistake in parsing bytes data or is there a better way to approach this problem to begin with? I've considered converting the image to Base64 before passing it to the API in a standard JSON payload but I'd like to know if passing the raw bytes data is an option, too.

P.S. replacing the code above with `img = Image.open(io.BytesIO(payload))` to bypass the file saving results in the same issue; it still appears that the payload is incomplete.

Thank you so much for your help!

**Comment by soulbliss** [comment]
@DragonDuck can you try showing the output for this line.

`print(payload, type(payload))`

Insert the above statement right after the definition of the _predict function_.

**Comment by RobertLucian** [comment]
@DragonDuck I just tried this as well and it looks like, for binary data, the `--data-binary` option is necessary instead of the `-d` option. Running `curl http://localhost:8890 -X POST -H "Content-Type: application/octet-stream" --data-binary @input_image.jpg` will send all 9792 bytes to the API.

From the [man](https://curl.se/docs/manpage.html) page:
```text
--data-binary <data>

This posts data exactly as specified with no extra processing whatsoever.

If you start the data with the letter @, the rest should be a filename. Data is posted in a similar manner as -d, --data does, except that newlines and carriage returns are preserved and conversions are never done.

Like -d, --data the default content-type sent to the server is application/x-www-form-urlencoded. If you want the data to be treated as arbitrary binary data by the server then set the content-type to octet-stream: -H "Content-Type: application/octet-stream".

If this option is used several times, the ones following the first will append data as described in -d, --data.
```

I also tried this with the `ab` GNU utility, and out of the box, it does seem to send all bytes correctly:
`ab -n 1 -c 1 -p input_image.jpg -T 'application/octet-stream' -rks 120 'http://localhost:8890/'`

**Comment by DragonDuck** [comment]
Oh, fantastic, thank you very much! I misunderstood the manpage, I guess, and thought it was equivalent to `--data` with the corresponding Content-Type header.
