### ISSUE TITLE
Is there any example for custom Spark code for data processing?

### ISSUE THREAD

**Issue by lylylytc** [cortexlabs/cortex#16]

**Comment by vishalbollu** [comment]
Currently, custom PySpark code can be used to create custom transformers and aggregators for data processing.  We do have several examples:

- https://github.com/cortexlabs/cortex/blob/master/examples/mnist/implementations/transformers/decode_and_normalize.py
- https://github.com/cortexlabs/cortex/blob/master/examples/reviews/implementations/aggregators/vocab.py

You can find a detailed explanation on how you can create and use your own custom [transformers](https://github.co/cortexlabs/cortex/blob/master/docs/applications/implementations/transformers.md) and [aggregators](https://github.com/cortexlabs/cortex/blob/master/docs/applications/implementations/aggregators.md) in these docs.

Hope this helps!
