### ISSUE TITLE
Remove bucket cluster configuration option

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1611]
### Implementation Notes

* the cluster name is currently used as a prefix for all paths in the bucket; that may no longer be necessary, but could remain as is.

### Motivation

Users can confuse the cortex internal bucket with their own which they use to save models

### Notes

- [ ] Double check that the AWS policy for the Cluster and Cluster management is updated accordingly

**Comment by RobertLucian** [comment]
Closed by https://github.com/cortexlabs/cortex/pull/2151.
