### ISSUE TITLE
GCP - Support private API and operator load balancers

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1621]
Here is the [guide](https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing) for private load balancers

**Comment by HodorTheCoder** [comment]
Let me know how I can help with this.   I am trying to find the options in gke.go and online to add to make this work.  Thanks.

**Comment by deliahu** [comment]
(just posting here in case anyone else is following the thread, since @HodorTheCoder and I connected via email)

I've created [this branch](https://github.com/cortexlabs/cortex/compare/0.26...gcp-private-lb) with a temporary implementation to test the feature.
