### ISSUE TITLE
GCP - Support preemptible (spot) instances

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1631]

**Comment by fandy** [comment]
Any updates on this? Would really make GCP worth using.

**Comment by deliahu** [comment]
@fandy thanks for reaching out. We don't have a timeline on this yet, but will keep you posted. Have you tried using Cortex on GCP with non-preemtable instances, or with spot instances on AWS?

**Comment by fandy** [comment]
> @fandy thanks for reaching out. We don't have a timeline on this yet, but will keep you posted. Have you tried using Cortex on GCP with non-preemtable instances, or with spot instances on AWS?

The reason we're sticking with GCP is because of better cost and usability over AWS. Even though they have spot instances and it integrates with Cortex it's still not worth switching from GCP.

We're going to use the Cloud SDK and cross our fingers we don't run into issues. How does Cortex compare to GCP/Cloud SDK?

**Comment by deliahu** [comment]
> The reason we're sticking with GCP is because of better cost and usability over AWS. Even though they have spot instances and it integrates with Cortex it's still not worth switching from GCP.

That makes sense, thanks for your explanation

> We're going to use the Cloud SDK and cross our fingers we don't run into issues. How does Cortex compare to GCP/Cloud SDK?

Cortex uses the Cloud SDK under the hood to manage GKE, GCR, GCS, etc

**Comment by deliahu** [comment]
@fandy I just wanted to follow up on this - we are planning to start working on supporting preemptible instances in the next week or two. It's still hard to say when it will be released, but hopefully in 2-4 weeks.
