### ISSUE TITLE
Your cluster's api gateway (in {region} with tag cortex.dev/cluster-name={cluster_name}) does not exist

### ISSUE THREAD

**Issue by rafaelsandroni** [cortexlabs/cortex#1641]
### Version

0.23.0

### Description

After starting the cluster with `cortex cluster up`. I'm trying to get the operator end-point, but I got a error related to api gateway:

$ cortex cluster info

`
using aws access key id ****KLVP and aws secret access key ****JMad from cache (to use different credentials, specify the --aws-key and --aws-secret flags)

cloudformation stack name                            status
eksctl-cortex-cluster                                CREATE_COMPLETE
eksctl-cortex-nodegroup-ng-cortex-operator           CREATE_COMPLETE
eksctl-cortex-nodegroup-ng-cortex-worker-on-demand   CREATE_COMPLETE

syncing cluster configuration ...

Traceback (most recent call last):
  File "get_api_gateway_endpoint.py", line 36, in <module>
    print(get_api_gateway_endpoint(), end="")
  File "get_api_gateway_endpoint.py", line 31, in get_api_gateway_endpoint
    f"your cluster's api gateway (in {region} with tag cortex.dev/cluster-name={cluster_name}) does not exist"
Exception: your cluster's api gateway (in us-east-1 with tag cortex.dev/cluster-name=cortex) does not exist
`

### Configuration

default config

### Steps to reproduce

1. cortex cluster up
2. cortex cluster info

### Expected behavior

To get information about cluster, specially operator end-point

### Actual behavior

Got a error related to api gateway, and broken the prompt

**Comment by rafaelsandroni** [comment]
Additionally, seems that the cortex dont created the api gateway, so, I've created an API and included the tag cortex.dev/cluster-name=cortex into api gateway. but error persists.

**Comment by deliahu** [comment]
@rafaelsandroni Thanks for creating the issue.

If you used a cluster configuration file (e.g. `cluster.yaml`) when creating your cluster, do you mind sharing its contents? If you didn't use a cluster config file, do you mind sharing how you answered the CLI prompts?

Also, did you see any errors when creating your cluster? If you still have the output from your `cortex cluster up` command, do you mind sharing that too?

Lastly, if you try to spin up a new cluster (with a different name), does it work as expected?

**Comment by deliahu** [comment]
@rafaelsandroni I just wanted to follow up on this, has your issue been resolved?

**Comment by deliahu** [comment]
@rafaelsandroni I'll go ahead and close this issue, let me know if you have additional questions
