### ISSUE TITLE
Can instance be kept alive for X amount of minutes

### ISSUE THREAD

**Issue by da-source** [cortexlabs/cortex#1692]
Is there way to keep instance running for specified amount of time, after it has been requested by curl?

**Comment by deliahu** [comment]
@da-source Assuming you are referring to Realtime APIs (rather than Batch APIs), and that you are referring to instances > 1 (rather than scale-to-zero), this can be configured in the [autoscaling configuration](https://docs.cortex.dev/workloads/realtime-api/autoscaling). Let me know if that's not what you were asking about!

**Comment by da-source** [comment]
> @da-source Assuming you are referring to Realtime APIs (rather than Batch APIs), and that you are referring to instances > 1 (rather than scale-to-zero), this can be configured in the [autoscaling configuration](https://docs.cortex.dev/workloads/realtime-api/autoscaling). Let me know if that's not what you were asking about!

the link that you've provided seems to be no longer working.

(sorry for a late reply)

**Comment by miguelvr** [comment]
> the link that you've provided seems to be no longer working.

this one should work fine: https://docs.cortex.dev/v/0.24/workloads/realtime/autoscaling

**Comment by da-source** [comment]
> > the link that you've provided seems to be no longer working.
> 
> this one should work fine: https://docs.cortex.dev/v/0.24/workloads/realtime/autoscaling
 
thanks. As I understand I need to set `window` to `600` to keep the instance from downscaling for 10 minutes, Is this correct?

**Comment by miguelvr** [comment]
> thanks. As I understand I need to set `window` to `600` to keep the instance from downscaling for 10 minutes, Is this correct?

that sounds about right

**Comment by da-source** [comment]
> > thanks. As I understand I need to set `window` to `600` to keep the instance from downscaling for 10 minutes, Is this correct?
> 
> that sounds about right

one more question: can the same be applied if i set the `min_instances` to 0?

**Comment by deliahu** [comment]
@da-source APIs can only be scaled down to a minimum of 1 replica. If you set `min_instances` to 0, in order to scale your cluster down to 0 instances, you will have to `cortex delete` your API.

**Comment by da-source** [comment]
> @da-source APIs can only be scaled down to a minimum of 1 replica. If you set `min_instances` to 0, in order to scale your cluster down to 0 instances, you will have to `cortex delete` your API.

So as I understand, it isn’t possible to create a cluster with 0 instances, but when I set min_instances to 0 in cluster.yaml, I was able to spin it up as usual. Was that a bug?

**Comment by deliahu** [comment]
@da-source It is possible to create a cluster with 0 instances, as long as there are no APIs deployed to the cluster. When a cluster is first created, there are no APIs running on it. Once there is an API deployed, the cluster will scale to at least 1 instance and will remain at at least 1 instance until all APIs have been deleted.

**Comment by da-source** [comment]
> @da-source It is possible to create a cluster with 0 instances, as long as there are no APIs deployed to the cluster. When a cluster is first created, there are no APIs running on it. Once there is an API deployed, the cluster will scale to at least 1 instance and will remain at at least 1 instance until all APIs have been deleted.

Just to clarify: can I have multiple APIs deployed with just one instance running by default, when those APIs are not being called or does each API need it’s own instance running at all time?

**Comment by deliahu** [comment]
Yes, you can have multiple APIs running on a single instance, as long as the sum of the `compute` requirements that you requested for your APIs don't exceed the amount available on the instance. You can check the instance capacity by running `cortex cluster info`, and specify your compute request with the `compute` field in the [api configuration](https://docs.cortex.dev/workloads/realtime/configuration)

**Comment by da-source** [comment]
> Yes, you can have multiple APIs running on a single instance, as long as the sum of the `compute` requirements that you requested for your APIs don't exceed the amount available on the instance. You can check the instance capacity by running `cortex cluster info`, and specify your compute request with the `compute` field in the [api configuration](https://docs.cortex.dev/workloads/realtime/configuration)

I see. Let’s say I’ll deploy 5 different API’s and specify max_instances to 5. Each API will take up compute of one whole instance. When I deploy a cluster, with those specs, will I have to pay for 5 instances running all the time or just for 1 one of them + extra IF I request one of the other APIs?

**Comment by da-source** [comment]
> > Yes, you can have multiple APIs running on a single instance, as long as the sum of the `compute` requirements that you requested for your APIs don't exceed the amount available on the instance. You can check the instance capacity by running `cortex cluster info`, and specify your compute request with the `compute` field in the [api configuration](https://docs.cortex.dev/workloads/realtime/configuration)
> 
> I see. Let’s say I’ll deploy 5 different API’s and specify max_instances to 5. Each API will take up compute of one whole instance. When I deploy a cluster, with those specs, will I have to pay for 5 instances running all the time or just for 1 one of them + extra IF I request one of the other APIs?

In other words, must minimum number of instances running equal to number of APIs deployed?

**Comment by deliahu** [comment]
> In other words, must minimum number of instances running equal to number of APIs deployed?

Not exactly, since multiple APIs can run on a single instance depending on the compute request of the API replica(s) and the capacity of your instance.

With 0 APIs running, the minimum is 0 instances

With 1+ APIs running, the minimum is 1 instance, but the minimum could be more (depending on the compute request of the API replica(s) and the capacity of your instance)
