### ISSUE TITLE
Two metrics have the same help value

### ISSUE THREAD

**Issue by wangzhao765** [cortexlabs/cortex#1697]
### Version

In master branch now.

### Description

https://github.com/cortexproject/cortex/blob/master/pkg/compactor/compactor.go
In line 236 and 240, these 2 metrics have the same help value.
It seems that cortex_compactor_blocks_marked_for_deletion_total means the total number of blocks marked for deletion,
and cortex_compactor_garbage_collected_blocks_total means the total number of blocks deleted after being marked?

### Configuration

(paste relevant `cortex.yaml` or `cluster.yaml` configuration)

### Steps to reproduce

1. ...
2. ...
3. ...

### Expected behavior

(describe the behavior you expected)

### Actual behavior

(describe the behavior you experienced)

### Screenshots

(optional)

### Stack traces

(error output from `cortex logs <api name>`)

```text
<paste stack traces here>
```

### Additional context

(optional)

### Suggested solution

(optional)

**Comment by deliahu** [comment]
@wangzhao765 I believe you intended to file this issue at https://github.com/cortexproject/cortex/issues, so I'll go ahead and close this issue here
