### ISSUE TITLE
How to make Cortex API call with JS?

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1734]
I'm trying to display Cortex API output on a simple webpage but I can't get a response for some reason.

Here's my code:

```
<html>
<body>
<p id="value" ></p>
<button class="get_values" onclick="startUpdate(event)">GET</button>

<script>
function startUpdate(e) {
  // e. preventDefault();
  // calling instantly
  updateP();
}

function updateP() {
  let url = "api-endpoint" 
  fetch('url', {
  method: "POST",
  headers: {"Content-type": "application/json;charset=UTF-8"}
})
    .then(response => response.json())
    .then(data => {
      let p = document.getElementById("value");
      // parsing the JSON value to string
      p.value = JSON.stringify(data);
    })
}
</script>
</body>
</html>
```

When I use `curl` command in the console to make a call, everything works fine.
How can I display the output in the HTML?

**Comment by deliahu** [comment]
@imagine3D-ai Here is an HTML file I created a while back to test CORS, and everything was working as expected. Does this work for you, and if so, are you able to borrow any of this code to get it working for you?

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Cortex CORS Test</title>

  <script>
    var HttpClient = function () {
      this.get = function (url, callback) {
        var xhr = new XMLHttpRequest();
        xhr.open("GET", url, true);
        xhr.onreadystatechange = function () {
          if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200)
            callback(xhr.responseText);
        }
        xhr.send(null);
      }
      this.post = function (url, payload, callback) {
        var xhr = new XMLHttpRequest();
        xhr.open("POST", url, true);
        xhr.setRequestHeader("Content-Type", "application/json");
        xhr.setRequestHeader("X-Custom-Header1", "hi");
        xhr.onreadystatechange = function () {
          if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200)
            callback(xhr.responseText);
        }
        xhr.send(payload);
      }
    }
    var client = new HttpClient();
    function predict() {
      document.getElementById("prediction").innerHTML = "";
      var endpoint = document.getElementById("endpoint").value
      var payload = document.getElementById("payload").value
      client.post(endpoint, payload, function (response) {
        document.getElementById("prediction").innerHTML = response;
      });
    }
    function clearPrediction() {
      document.getElementById("prediction").innerHTML = "";
    }
  </script>
</head>

<body id="home">
  <div id=main>
    <div>API endpoint:</div>
    <div><input type="text" id="endpoint" size="120" style="margin-bottom: 1em;"></div>
    <div>JSON payload:</div>
    <div><textarea id="payload" rows="20" cols="120" style="margin-bottom: 1em;"></textarea></div>
    <div><button type="button" onclick="predict()" style="margin-bottom: 1em;margin-right: 0.5em;">Predict</button>
      <button type="button" onclick="clearPrediction()" style="margin-bottom: 1em;">Clear</button></div>
    <div id=prediction></div>
  </div>
</body>

</html>
```

**Comment by imagine3D-ai** [comment]
> @imagine3D-ai Here is an HTML file I created a while back to test CORS, and everything was working as expected. Does this work for you, and if so, are you able to borrow any of this code to get it working for you?
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> 
> <head>
>   <meta charset="utf-8">
>   <title>Cortex CORS Test</title>
> 
>   <script>
>     var HttpClient = function () {
>       this.get = function (url, callback) {
>         var xhr = new XMLHttpRequest();
>         xhr.open("GET", url, true);
>         xhr.onreadystatechange = function () {
>           if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200)
>             callback(xhr.responseText);
>         }
>         xhr.send(null);
>       }
>       this.post = function (url, payload, callback) {
>         var xhr = new XMLHttpRequest();
>         xhr.open("POST", url, true);
>         xhr.setRequestHeader("Content-Type", "application/json");
>         xhr.setRequestHeader("X-Custom-Header1", "hi");
>         xhr.onreadystatechange = function () {
>           if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200)
>             callback(xhr.responseText);
>         }
>         xhr.send(payload);
>       }
>     }
>     var client = new HttpClient();
>     function predict() {
>       document.getElementById("prediction").innerHTML = "";
>       var endpoint = document.getElementById("endpoint").value
>       var payload = document.getElementById("payload").value
>       client.post(endpoint, payload, function (response) {
>         document.getElementById("prediction").innerHTML = response;
>       });
>     }
>     function clearPrediction() {
>       document.getElementById("prediction").innerHTML = "";
>     }
>   </script>
> </head>
> 
> <body id="home">
>   <div id=main>
>     <div>API endpoint:</div>
>     <div><input type="text" id="endpoint" size="120" style="margin-bottom: 1em;"></div>
>     <div>JSON payload:</div>
>     <div><textarea id="payload" rows="20" cols="120" style="margin-bottom: 1em;"></textarea></div>
>     <div><button type="button" onclick="predict()" style="margin-bottom: 1em;margin-right: 0.5em;">Predict</button>
>       <button type="button" onclick="clearPrediction()" style="margin-bottom: 1em;">Clear</button></div>
>     <div id=prediction></div>
>   </div>
> </body>
> 
> </html>
> ```

I tried running this, but nothing happened when I pressed 'predict' button.
After checking logs using `cortex logs enpoint --env aws` I got this message:
`2020-12-24 17:15:07.619385:cortex:pid-240:INFO:405 Method Not Allowed OPTIONS /predict`

What can be the cause of this?

**Comment by deliahu** [comment]
@imagine3D-ai This could be related to CORS. Are you running Cortex in the `local` environment or on `aws`? Also, which version of cortex are you using? CORS with the local version of Cortex is not supported, but the latest version of Cortex running on an AWS cluster should work.

**Comment by imagine3D-ai** [comment]
> @imagine3D-ai This could be related to CORS. Are you running Cortex in the `local` environment or on `aws`? Also, which version of cortex are you using? CORS with the local version of Cortex is not supported in all cases, but the latest version of Cortex running on an AWS cluster should work.

It works after updating to latest version. Thanks!
