### ISSUE TITLE
Support user-defined Starlette middleware

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1737]
### Motivation

Enforcing payload structure, gzipping response, etc

### Workarounds

Objects of type [starlette.responses.Response](https://www.starlette.io/responses/#response) can be returned by `predict()` ([docs](https://docs.cortex.dev/workloads/realtime/predictors#api-responses)). Therefore, it is possible implement a helper method that validates and zips the response and returns a `starlette.responses.Response` object, and use something like `return validate_and_zip(data)` at the end of the `predict()` function.

**Comment by miguelvr** [comment]
It would be nice to do so with a decorator. Maybe we would need the user to use a cortex package from the predictor.

Something along the lines of

```python
@cortex.middleware(my_middleware)
class PythonPredictor:
    (...)
```
