### ISSUE TITLE
Auto-spin up and spin down APIs on demand

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1743]
I'm considering a project involving a dozen multiple inference APIs. As I understand, when deploying an API to a cluster, each API has at least 1 instance which constantly runs on the cluster. Is there a way to spin-up an API when user requests it and then spin the API down when the job is complete, to reduce the costs of running multiple instances on a single cluster?

Let's say that one instance costs 0.5$/hour and the fixed price of running a cluster is 0.2$/hour. Then deploying 10 APIs on a cluster costs 0.5 * 10 + 0.2 = 5.2/hour*24 = 124.8$/day. If instead it would be possible to spin-up/spin-down the APIs on demand, only when user requests them, the cost of running a cluster when no API calls are being made, would be 0.2$/hour = 4.8$/day (which is considerably less). 

Is there a way to achieve reduced costs of running a cluster with multiple APIs?

(I considered running a VM with Cortex installed, which would accept calls to deploy an API, get the endpoint, make API call and then spin down the API if it's not being used and no instances are needed to be running; is this a good idea?)

**Comment by imagine3D-ai** [comment]
> I'm considering a project involving a dozen multiple inference APIs. As I understand, when deploying an API to a cluster, each API has at least 1 instance which constantly runs on the cluster. Is there a way to spin-up an API when user requests it and then spin the API down when the job is complete, to reduce the costs of running multiple instances on a single cluster?
> 
> Let's say that one instance costs 0.5$/hour and the fixed price of running a cluster is 0.2$/hour. Then deploying 10 APIs on a cluster costs 0.5 * 10 + 0.2 = 5.2/hour*24 = 124.8$/day. If instead it would be possible to spin-up/spin-down the APIs on demand, only when user requests them, the cost of running a cluster when no API calls are being made, would be 0.2$/hour = 4.8$/day (which is considerably less).
> 
> Is there a way to achieve reduced costs of running a cluster with multiple APIs?
> 
> (I considered running a VM with Cortex installed, which would accept calls to deploy an API, get the endpoint, make API call and then spin down the API if it's not being used and no instances are needed to be running; is this a good idea?)

Another solution might be to accept payload which would specify which model needs to be downloaded/used (instead of downloading pre-specified model on init) and then a single API could handle multiple all the models. Is this a better to implement this?

**Comment by deliahu** [comment]
@imagine3D-ai There are a few methods to consider

1. Deploy multiple models in a single API. You can load all of the models into memory on init, and then have a query parameter in the request or a field in the request payload which specifies which model to use. Here is a simple [example](https://docs.cortex.dev/workloads/multi-model/example#define-a-multi-model-api).
2. Use a [Batch API](https://docs.cortex.dev/workloads/batch): if your requests do not need immediate responses (can be asynchronous) and take some time to complete, this is a good approach since it scales to zero (each request would create a replica to run the request on, so it would not be efficient if requests are quick to handle)
3. It is possible to run multiple separate APIs on a single instance, depending on the size of the instance and the compute requirements of the API. You can configure the compute requests for the API replicas in the `compute` section in the [API configuration](https://docs.cortex.dev/workloads/realtime/configuration), and check the capacity of your instance with `cortex cluster info`. If you are trying to keep cost/complexity down by keeping everything on a single instance, probably option 1 will be better. This approach could be better if your APIs need to independently autoscale

Do any of these options seem like they would work?

**Comment by imagine3D-ai** [comment]
> @imagine3D-ai There are a few methods to consider
> 
> 1. Deploy multiple models in a single API. You can load all of the models into memory on init, and then have a query parameter in the request or a field in the request payload which specifies which model to use. Here is a simple [example](https://docs.cortex.dev/workloads/multi-model/example#define-a-multi-model-api).
> 2. Use a [Batch API](https://docs.cortex.dev/workloads/batch): if your requests do not need immediate responses (can be asynchronous) and take some time to complete, this is a good approach since it scales to zero (each request would create a replica to run the request on, so it would not be efficient if requests are quick to handle)
> 3. It is possible to run multiple separate APIs on a single instance, depending on the size of the instance and the compute requirements of the API. You can configure the compute requests for the API replicas in the `compute` section in the [API configuration](https://docs.cortex.dev/workloads/realtime/configuration), and check the capacity of your instance with `cortex cluster info`. If you are trying to keep cost/complexity down by keeping everything on a single instance, probably option 1 will be better. This approach could be better if your APIs need to independently autoscale
> 
> Do any of these options seem like they would work?

Batch API seems to me to be the most plausible choice, since my models are quite large and can’t be fitted on a single instance.
It takes some time to get a response from my model (about 10-12 seconds), could Batch API make this even longer?
Can I specify which model should be downloaded with Batch API, by sending that information via payload? I haven’t yet tried using Batch API and all the other Cortex examples I’ve seen, download a file on init, and I’m wondering if this could be determined by predict(payload) function or something alike.

**Comment by deliahu** [comment]
Batch APIs are asynchronous, so the client will immediately get a response back. It would be up to you to write the prediction result to a location where the client can access it once it's ready. However, it will take minutes for each batch job to start up, so if you are making requests just one at a time, this would not be a good approach. It's designed for jobs that take many minutes to run.

If your models are quite large and only can fit one or a few per instance, then your best bet is to use an API per model, or to use multi-model caching. with multi-model caching, you can define how many models are kept in memory at a time. If a request comes in which requires a model that is not in memory, it will load the new model and evict an existing model from memory. The request is still synchronous and models can all be kept on disk, so how long it takes for the response to come back depends on how long it takes to load the model from disk to memory and then run the inference. Here are the [relevant section in the docs](https://docs.cortex.dev/workloads/realtime/models#multi-model-caching), but you will probably want to read the entire page, since multi-model caching relies on a few other concepts described above.

**Comment by imagine3D-ai** [comment]
> Batch APIs are asynchronous, so the client will immediately get a response back. It would be up to you to write the prediction result to a location where the client can access it once it's ready. However, it will take minutes for each batch job to start up, so if you are making requests just one at a time, this would not be a good approach. It's designed for jobs that take many minutes to run.
> 
> If your models are quite large and only can fit one or a few per instance, then your best bet is to use an API per model, or to use multi-model caching. with multi-model caching, you can define how many models are kept in memory at a time. If a request comes in which requires a model that is not in memory, it will load the new model and evict an existing model from memory. The request is still synchronous and models can all be kept on disk, so how long it takes for the response to come back depends on how long it takes to load the model from disk to memory and then run the inference. Here are the [relevant section in the docs](https://docs.cortex.dev/workloads/realtime/models#multi-model-caching), but you will probably want to read the entire page, since multi-model caching relies on a few other concepts described above.

I've read through the link that you've provided and I have a few questions about multi-model-caching: 
If a single model weighs around 5Gb, and I specify `cache_size` to 1 (to keep only 1 model in `cache`) and `disk_cache_size` to 9 (to keep the rest of the models in disk), what happens if the instance doesn't have enough memory to keep all the models on disk? If I use `m5.large` instance, it has about 8Gb of space, so it will fit only 1 model, and I'm not sure how it will work with multi-model-caching. Does `disk_cache_size` mean that all the files will be downloaded to user's local device that is being used?

**Comment by RobertLucian** [comment]
@imagine3D-ai instances come with memory (RAM) and some disk capacity. The `cache_size` is referring to the max number of models that will get loaded in memory (RAM) and `disk_cache_size` to the max number of models kept on disk (i.e. as far as I remember, the EC2 instances are configured with 50 GB by default). Disk storage comes cheaper than RAM memory.

I believe that if a model doesn't fit in memory, an OOM error will be reported by Cortex. If a model doesn't fit on disk, then that is an undefined situation - the user must ensure that no more than X amount of GBs are used on disk.

Also, a model's size in GB (on disk) doesn't translate to how much memory will be required upon loading. From personal experience, I can tell that there's more that it takes than what a model takes on disk - you need to take into account the weights + inputs + overhead.

> Does disk_cache_size mean that all the files will be downloaded to user's local device that is being used?

`disk_cache_size` represents the maximum number of models that _can_ be downloaded and kept on disk at any point in time. When the API starts, by default there won't be any models on-disk/in-memory, and as requests come in, that pool gets populated until it hits that threshold, after which, the models are evicted from disk/memory based on their LRU.

I recommend going through the _models_ page we have [here](https://docs.cortex.dev/workloads/realtime/models) to get a better understanding of this.

**Comment by imagine3D-ai** [comment]
@RobertLucian 
Thanks, for answering! Could you take a look at this code and say if I'm missing something:

```
import boto3
import sys
import os


class PythonPredictor:
    def __init__(self, config, python_client):
    	s3 = boto3.client('s3', aws_access_key_id='key', 
    		aws_secret_access_key='s-key')
    	self.client = python_client

    def load_model(self, model_path):
        return load_from_disk(model_path)

    def predict(self, payload, query_params):
      file = self.client.get_model(query_params["model"])
      with open(file) as f:
      	#do something
      return file
```

In the scenario above, I want for each instance to download only a single model/file of user's choice by passing (`query_params['model']` argument), from my bucket, and then do something with the file. Once the specified file is downloaded, should I use the same `predict()` function to load and perform further operations on the file or is it better to use `post_predict()` function?

As I understand `client.get_model()` uses `load_from_disk()` which accesses `cortex.yaml` to get directory structure of S3 bucket where models/files are located, is this correct? Also when using live-reloading using `client.get_model`, how should the aws-access-keys be passed?

**Comment by RobertLucian** [comment]
@imagine3D-ai looked at code and I have a few things to say.

`load_model` is a method that receives an argument that points to a local directory path. That directory path contains the model from your S3/GCS resource as it was _synchronized_ by Cortex for you - you can see the models that were synchronized for you by running `cortex get <api-name>`. That means that in the `load_model` method, you are supposed to actually load the model into memory and then return that loaded model. That returned value is the same as the one that's retrieved by `client.get_model` method (for your given model).

In the `predict` method, you run the prediction on your desired model. If multiple models are present, you would typically use the query params to get the model name, then you retrieve the model using `client.get_model` method (without caring how you got the model there), then you run the inference, and finally, you return the result.

Now, the returned value of `load_model` (and therefore of `get_model`) can be anything, there are no enforcements in that regard, but that object (value) should be loaded from disk as specified by `load_model`.

Your predictor implementation should have this general layout

```python
class PythonPredictor:
    def __init__(self, config, python_client):
    	self.client = python_client

    def load_model(self, model_path):
        # some function/sequence of instructions to load a model into memory
        model = load_model_from_disk(model_path)
        return model

    def predict(self, payload, query_params):
      # get the model
      model = self.client.get_model(query_params["model"])
      
      # assuming the model has a run method
      result = model.run(payload)

      return result
```

---

I recommend going through [this page](https://docs.cortex.dev/workloads/realtime/models) that explains how live-reloading/multi-model-caching actually works. Let me know if there's anything confusing in there that you think we should address/modify. We are open to suggestions!

**Comment by imagine3D-ai** [comment]
I see. One last question: if I set compute requirement to 5G in cortex.yaml and use a cluster with aws instances that have only about 5G memory allocatable, will that mean that each new Cortex API request will instantiatr a brand new AWS instance?

**Comment by deliahu** [comment]
@imagine3D-ai Yes that is correct. And if your instance had 10G of memory, cortex would put 2 APIs on that instance (assuming the CPU requests of the APIs also fit when added up). Keep in mind that the memory available to your APIs is slightly less than the instance's capacity: `cortex cluster info` will show you how much memory is available to APIs on each instance.
