### ISSUE TITLE
How to make Cortex available in AWS Lambda?

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1780]
I'm trying to create a microservice to manage my cluster via Cortex and Lambda. AWS Lambda requires python dependencies to be packaged and uploaded as a `.zip` files. How can I package Cortex library to `.zip`?

**Comment by mutal** [comment]
this question became duplicated for some reason

**Comment by imagine3D-ai** [comment]
this question got duplicated for some reason
