### ISSUE TITLE
Tensorflow predictor does not work with tensorflow-io ops

### ISSUE THREAD

**Issue by lminer** [cortexlabs/cortex#1783]
I've created a frozen graph for serving that incorporates `tensorflow-io` ops. Although I can run the model fine locally, when I try to run it on the cluster, I get the following error. It seems like this has something to do with how the tf-serving image is built. I didn't do anything special to get this running locally, so maybe it just comes down to having both `tensorflow-io` and `tensorflow` installed on the tensorflow-serving image. I tried adding `tensorflow-io` to the requirements.txt, but that didn't help. Does the requirements.txt apply to the tensorflow-serving image or just to the api image?

```
2021-01-14 18:42:20.495639: E external/org_tensorflow/tensorflow/core/grappler/optimizers/meta_optimizer.cc:592] function_optimizer failed: Not found: Op type not registered 'IO>AudioReadableInit' in binary running on  Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing
(e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```

Here's the related [issue ](https://github.com/tensorflow/io/issues/1268) on the `tensorflow-io` repo.

**Comment by deliahu** [comment]
@lminer `requirements.txt` does not apply to the tensorflow-serving image (Python is not actually installed on that image, since the tensorflow-serving implementation is in C++). Do you know if there is there a system package that might need to be installed?

Also, was it working locally with the TensorFlow predictor type? This is interesting to me, since that should be the same exact image that is running in the cluster.

**Comment by lminer** [comment]
I haven't tried it with the predictor type. I only tried it in a separate jupyter notebook in an conda environment with both tensorflow-io and tensorflow installed. I doubt it would work locally with the tensorflow predictor.

I don't know if there's a system package. I doubt it since I haven't installed anything special locally. My guess is that you need tensorflow-io installed and linked to tensorflow. Maybe the python package does this...

**Comment by lminer** [comment]
@deliahu looks like this is a known problem and one that is stalled. See [here](https://github.com/tensorflow/io/issues/414) and [here](https://github.com/tensorflow/serving/issues/1411).

**Comment by deliahu** [comment]
@lminer Thanks for the update

**Comment by deliahu** [comment]
I'll go ahead and close this ticket here since it seems to be an issue that needs to be addressed by the TF Serving team. Users can also use the Python predictor type as an alternative to TF Serving.
