### ISSUE TITLE
Add ability to share file system between tensorflow serving image and tensorflow predictor

### ISSUE THREAD

**Issue by lminer** [cortexlabs/cortex#1792]
### Description

Would be nice to be able to write to some location in the `TensorflowPredictor` that could be accessed from within `tensorflow-serving` and vice-versa. This is just a docker cli option, no?

### Motivation

This would be a way to get around the issue with passing large amounts of data back and forth between the api and tensorflow-serving as recorded [here](https://github.com/cortexlabs/cortex/issues/1774#issuecomment-759910662).

**Comment by deliahu** [comment]
@lminer When running in a cluster, the `/mnt` path is shared across the containers; let us know if you're able to get it working, and we'll add it to the docs. Thanks for the suggestion!

**Comment by lminer** [comment]
Huzzah. It works!

**Comment by deliahu** [comment]
Awesome! I've added a note to the docs in https://github.com/cortexlabs/cortex/pull/1802
