### ISSUE TITLE
error: failed to zip project folder

### ISSUE THREAD

**Issue by vtrokhymenko** [cortexlabs/cortex#1793]
runed `$ cortex cluster up --config cluster.yaml`
but after `$ cortex deploy text_generator.yaml` get 
`do you want to upload env/lib/python3.8/site-packages/cortex/binary/cli (99.0 MiB)? (y/n):`
and the tail is `error: failed to zip project folder: <PATH>/env/include/python3.8: no such file`

how to resolve this error?

**Comment by RobertLucian** [comment]
@vtrokhymenko what I notice is that you're trying to upload the environment directory for your Cortex API - you don't have to do this as the API has its environment already configured. In order for this directory `env` to be ignored, you need to add it to `.dockerignore`, which follows the same syntax and behavior as a `.gitignore` file:

```gitignore
# .dockerignore
dev/
```

I also recommend reading [this page](https://docs.cortex.dev/workloads/realtime/predictors), which explains more about this subject.

**Comment by vtrokhymenko** [comment]
thx, in the near future, get to testing 
and more, can i use `.cortexignore` instead `.dockerignore` to add my `env` folder?

**Comment by deliahu** [comment]
>can i use `.cortexignore` instead `.dockerignore` to add my env folder?

@vtrokhymenko I don't fully understand your question, do you mind explaining more about what you would like to do?

**Comment by vtrokhymenko** [comment]
about this
> .cortexignore file, which follows the same syntax and behavior as a .gitignore file.

**Comment by deliahu** [comment]
Oh I see! Yes, I think @RobertLucian meant to write `.cortexignore` instead of `.dockerignore` (I didn't notice that either when I read it).

You can use `.cortexignore` to ignore directories or files when packaging your API, and it follows the same syntax as `.gitignore`.
