### ISSUE TITLE
Consider: Add gzip configuration to realtime API spec

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1794]
### Description

If set to true, the response will automatically be gzipped (via the gzip middleware in [Starlette](https://www.starlette.io/middleware/#gzipmiddleware) or [FastAPI](https://fastapi.tiangolo.com/advanced/middleware/#gzipmiddleware)).

**Comment by jgingerexscientia** [comment]
This can be done manually using 
```
from starlette.responses import Response
import gzip

return Response(
    gzip.compress(bytes(json.dumps(result), "utf-8")),
    status_code=200,
    headers={"Content-Encoding": "gzip"},
    media_type="application/json",
)

```

**Comment by deliahu** [comment]
I'll go ahead and close this issue since the above solution is the recommended approach
