### ISSUE TITLE
Is it possible to scale cluster back down to 0 replicas when no APIs are running?

### ISSUE THREAD

**Issue by da-source** [cortexlabs/cortex#1813]
I specified `min_instances=0` in `cluster.yaml` and after launching the cluster, it costed `0.19$/hour`. After deploying and deleting an API, the cost of running the cluster was `$0.30/` and that was due to an idle EC2 replica running, even though no APIs were deployed. Is it possible to take down all the replicas, when no APIs are deployed, so that there won't be an idle instance running?

**Comment by deliahu** [comment]
da-source The behavior you desire is the intended behavior: It should terminate the extra instance if there are no APIs.

Do you mind confirming that there are no APIs by running `cortex get`? If none are listed and your cluster is still in this state, do you mind running `cortex cluster info --debug` and sending the cluster debug file to us at dev@cortex.dev so we can take a look?

**Comment by miguelvr** [comment]
@da-source Bear in mind that there will always be at least one instance running for the cortex operator, which has costs and cannot be scaled down to zero

**Comment by da-source** [comment]
@deliahu I tried deploying two APIs and then deleting them, I made sure that no APIs were running and then called `cortex cluster info`:
```
your cluster currently costs $0.28 per hour

aws resource                            cost per hour
1 eks cluster                           $0.10
2 instances for your apis               $0.076 total
2 50gb ebs volumes for your apis        $0.014 total
1 t3.medium instance for the operator   $0.0416
1 20gb ebs volume for the operator      $0.003
2 network load balancers                $0.045 total

your cluster has 0 API replicas running across 2 instances

instance type   lifecycle   replicas   CPU (requested / total allocatable)   memory (requested / total allocatable)
m5.large        spot        0          0m / 1290m                            0 / 6824584Ki
m5.large        spot        0          0m / 1290m                            0 / 6824584Ki
```

It shows that no APIs are running, but it appears that Cortex didn't delete those two instances

**Comment by da-source** [comment]
@deliahu I have sent debug file to dev@cortex.dev

**Comment by da-source** [comment]
@deliahu It was a timing mistake on my part, it takes about 10 minutes for replicas to get deleted.
