### ISSUE TITLE
How to automatically delete API after X amount of time?

### ISSUE THREAD

**Issue by da-source** [cortexlabs/cortex#1818]
Is there a way to auto-delete an API after some time after it has been deployed? I don’t want APIs to be running longer than a certain period of time and deleting them manually wouldn’t be ideal. Is it possible to specify the amount of time API will be deployed in the predictor and then set API to auto-delete itself after that timeperiod has passed?

**Comment by da-source** [comment]
Perhaps creating a Python Cortex cluster client within the API’s predictor.py and then calling api_delete() on itself?

**Comment by deliahu** [comment]
@da-source perhaps that could work, although if I understand your proposal correctly, you would still need to make the deletion request at the correct time. What are you thinking in terms of how to know when to make the deletion request? One approach could be a cron job or a lambda function that runs on some interval, and uses the python client to check for stale APIs (the responses from `get_api` and `list_apis` include the time the API was last updated). Do you think that would work, or did you have a different idea?

**Comment by da-source** [comment]
@deliahu 
I was thinking about setting a timer inside a predictor on init() and also specifying the time during which a replica will be alive to be as long as or longer than the timer’s timeperiod, so it won’t spin down and timer won’t have to be restarted. And then calling api_delete() when timer runs out. Whould that work? (considering that API will be deployed once and won’t be updated)

**Comment by deliahu** [comment]
@da-source Yes that should work! (assuming that the API will be deployed once; every time it's updated it would just restart the timer).

Something like this:

```python
import threading
import cortex

client = cortex.cluster_client(
    name="aws",
    provider="aws",
    operator_endpoint="https://ac63318382b184ce7b03026c5f30fff3-b6bfe88ba5fe46e8.elb.us-west-2.amazonaws.com",
    aws_access_key_id="***",
    aws_secret_access_key="***",
)


def delete_api():
    client.delete_api("my-api")


class PythonPredictor:
    def __init__(self, config):
        # initialize your model

        threading.Timer(20, delete_api).start()

    def predict(self, payload):
        return "ok"
```

**Comment by da-source** [comment]
@deliahu If I set the 'self-destruct' timer to 30 minutes, do I need to set `downscale_stabilization_period` to be 35 minutes (to make sure that replica won't spin down before the timer runs out) or is there some other parameter in `cortex.yaml` that needs to be changed?

**Comment by deliahu** [comment]
I don't think you will have to make a change to `downscale_stabilization_period`, since the API replicas will not scale below 1. I also can't think of any other configuration parameters that would need to be changed
