### ISSUE TITLE
Can't pickle imported classes

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#1826]
### Version

<= 0.27

### Description

Passing in an imported class implementation results in a module not found error. For example:

```
from foo.bar import PythonPredictor

client.create_api(predictor=PythonPredictor,...)
```

Will result in:
```
ModuleNotFoundError: No module named 'foo'
```

Related to #1824 

### Suggested solution

Currently dill is being used pickle class definitions. When an imported class definition is pickled, only the reference is pickled and not the class definition itself resulting in the ModuleNotFoundError when the pickle is unpickled in Cortex serving container.

Here is some potential pseudocode for how `create_api` could be updated:

```python
def create_api(predictor,...):
  ...
  if interactive_repl():
    pickle(predictor)  # write predictor.pickle to temp project dir
  if class_definition_is_inlined:
    dill.source.importable(predictor, source=True)  # write predictor.py to temp project dir
  if class_definition_imported:
    copy_file_containing_class(predictor) # write predictor.py to temp project dir
  ...
```

**Comment by htahir1** [comment]
Perhaps a naive comment: Why is there a necessity to pickle in the first place? Isn't it easier to base64 encode the referenced file / module or zip it or some alternative method?

**Comment by vishalbollu** [comment]
As far as I know, pickling is the only way to package a class definition that has been defined in an interactive REPL such as jupyter notebooks. 

`cortex.create_api(project_dir=".", api_spec=api_spec)` does zip the directory/module. In the `api_spec` you can specify the file path (relative to the project_dir) to a predictor.py file containing a predictor class definition. This approach doesn't require any pickling. The project_dir approach is recommended approach in non jupyter settings because the entire project directory is sent to the serving container. Other files in your project can be imported in your predictor implementation and you can have imports at the top of predictor.py rather having imports within function scope.

**Comment by htahir1** [comment]
I see. Wouldn't it then make more sense in the context of an interactive REPL to copy the referenced class to a temp for and then trigger the project dir referencing that temp for? That way the two cases both do the same thing but with just one additional step at the start

**Comment by vishalbollu** [comment]
Apologies for the delayed response, other higher priority issues came up. We are still planning to address this issue in the next release (which is scheduled for next week).

The design you've suggested does make sense and that is how `create_api` is currently implemented. When you invoke `cx.create_api(predictor=PythonPredictor)` a temporary project directory is created and a pickled version of the PythonPredictor is written to that project directory. The pickling aspect is causing us problems when the predictor is imported (as you've noticed) and in some environments #1824. I have updated the proposed design accordingly to clearly reflect the different scenarios that need to be handled and how we plan on handling them.
