### ISSUE TITLE
Support a distributed model caching mechanism

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1828]
### Description

For example, if you serve 100 models across 20 instances, where each instance can hold 2 models in memory, ideally the system would behave like a single LRU cache of size 40. Requests would be routed to replicas on which the requested model is already loaded (if exists), otherwise routed to a replica which will evict the least recently used. One open question is how to handle autoscaling, when it may be necessary to load the same model on multiple instances.

**Comment by jminuscula** [comment]
@miguelvr could you please share context on why this issue was closed? Very interested in following up. Thank you!

**Comment by miguelvr** [comment]
@jminuscula we have stopped the support for multi-model caching as of version 0.36. 

You are now able to run any arbitrary docker container in Cortex, so you could potentially use other solutions for multi-model caching. The Triton Inference Server comes to mind as a potential useful solution

**Comment by ShantanuNair** [comment]
@miguelvr  Any pointers on how to do this with triton? Just set the instance_groups settings and ELB will automatically see what's available?
