### ISSUE TITLE
If predictor had dependencies, how to add those dependency

### ISSUE THREAD

**Issue by dorkforcesron** [cortexlabs/cortex#1838]
This tool is really nice tool. 
I'm new of this tool, one basic question is that when I deploy one real-time API, how can add those dependencies if my predictor will need other source code?
For example, I want to deploy Wav2lip model (https://github.com/Rudrabha/Wav2Lip) for large scale inference. It will depends on other codes? Can I package one new docker images and use that images which includes dependency? Then I develop one new predictor and parse the input which needed for inference.  

python inference.py --checkpoint_path <ckpt> --face <video.mp4> --audio <an-audio-source> 

https://github.com/dorkforces/Wav2lip

Thanks
Ron

**Comment by RobertLucian** [comment]
@dorkforcesron you have a few ways of customizing your API.
1. For installing Python dependencies with pip or conda, check out this [page](https://docs.cortex.dev/workloads/managing-dependencies/python-packages).
2. For installing generic system packages, check out [this](https://docs.cortex.dev/workloads/managing-dependencies/system-packages).
3. For creating your own image using ours as a base, check out [this](https://docs.cortex.dev/workloads/managing-dependencies/images). For this, we recommend using the slim images.

**Comment by dorkforcesron** [comment]
@RobertLucian Appreciate your quick response, I will try it on my side.
