### ISSUE TITLE
How to make Cortex XmlHttpRequest on HTTPS page?

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1874]
I have website which runs on `https://` and I can't make Cortex API XmlHttpRequest requests over it.

When running on localhost using `http://`, everything works fine:

```
function postData(url = '', data = {}) {
  // Default options are marked with *
  const response = await fetch(url, {
    method: 'POST', // *GET, POST, PUT, DELETE, etc.
    mode: 'cors', // no-cors, *cors, same-origin
    cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
    credentials: 'same-origin', // include, *same-origin, omit
    headers: {
      'Content-Type': 'application/json'
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },
    redirect: 'follow', // manual, *follow, error
    referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
    body: JSON.stringify(data) // body data type must match "Content-Type" header
  });
  return response.json(); // parses JSON response into native JavaScript objects
}
```

But when making the same request on a `https://` page gives following:

`Mixed Content: The page at 'https://www.@' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://a6cc8d4dee22a448e81bb29862332bf0-93580d7c9d7d2256.elb.us-east-2.amazonaws.com/newtest-user'. This request has been blocked; the content must be served over HTTPS.`

How can I access Cortex API over HTTPS?

**Comment by miguelvr** [comment]
If you don't need a custom domain: 
https://docs.cortex.dev/clusters/cortex-cloud-on-aws/index/https

If you need a custom domain:
https://docs.cortex.dev/clusters/cortex-cloud-on-aws/index/custom-domain

**Comment by imagine3D-ai** [comment]
Part of my application requires dynamically creating and invoking Cortex APIs, but in the links that you’ve provided, https must be enabled manually by going to the AWS Console. Is there a way to programatically  make Cortex APIs `https` available?

**Comment by miguelvr** [comment]
You would just have to do that once, to configure the APIs gateway. In your case, it would be easier to use the AWS API Gateway for easy HTTPS setup (https://docs.cortex.dev/clusters/cortex-cloud-on-aws/index/https)

**Comment by imagine3D-ai** [comment]
I'm trying to implement `https:// `by creating the custom domain. In this tutorial (https://docs.cortex.dev/clusters/cortex-cloud-on-aws/index/custom-domain), in the `Configure DNS` part, it is said that I need to choose a subdomain. I'm using GoDaddy to host my website and I was wondering if I need to explicitly create my subdomain (`api.my-domain.net`). I followed through the instructions without explicitly creating the subdomain with GoDaddy and when I tried accessing the `api.my-domain.net`, there seem to be nothing there, just like with `api.cortexlabs.dev`. Also, when making a curl request with `api.my-domain.net`, I got an `curl: (6) Could not resolve host:` error. Was it due to not creating the subdomain w/ GoDaddy, before following through the instructions?

**Comment by deliahu** [comment]
@imagine3D-ai You will need to update your DNS settings in GoDaddy to point your subdomain to the AWS Route 53 name servers. This is accomplished by adding an `NS` record with GoDaddy (the guide you linked to shows how to do the same thing with Google Domains, but it should be similar with GoDaddy). Here is a [GoDaddy guide](https://www.godaddy.com/help/add-an-ns-record-19212) which should help.

**Comment by imagine3D-ai** [comment]
I've added the GoDaddy `NS` records yesterday and I still get the `curl: (6) Could not resolve host:` error today when testing connectivity by:

1) redeploying the cluster
2) deploying an api
3) making subdomain `curl` request: `curl https://api.mydomain.net/testapi`

GoDaddy says that it can take up to 48 hours for the new records to be active, so maybe that is the issue and I'll try again later.

When re-testing today, I went to the `AWS Route 53` Console to make `load balancer` endpoint alias change, assuming that the cluster that I redeployed will have a new `load balancer` endpoint, but it didn't, although the `operator endpoint` endpoint was different from the one my cluster had yesterday. I hope that's normal.

**Comment by deliahu** [comment]
I would have expected the DNS to be good to go by now, so my guess is that something else is not configured correctly.

Do you mind sending screenshots of your DNS record and Route 53 configuration, as well as your cluster configuration file? Also, if you try `curl` with the load balancer URL (not the custom domain), does it work? You can try both `http` and `https` (when using `https` with the load balancer url, you will need to use `curl -k` to skip certificate verification)

**Comment by imagine3D-ai** [comment]
I've sent the files to `dev@cortex.dev`

When doing the `curl` requests to my http and https (`curl -k`) load balancer and nothing happens. Is this normal?

**Comment by deliahu** [comment]
@imagine3D-ai This is not normal, and we should first determine why the load balancer URL is not working.

When you run `cortex get API_NAME`, it should print out the endpoint for your API. If you use curl to make a GET request to that endpoint (e.g. `curl http://a6b379e30fac64b4da92b3856c47a647-95c3df6d162d5fd7.elb.us-west-2.amazonaws.com/iris-classifier`), do you get a response back?

**Comment by imagine3D-ai** [comment]
Yes, with `curl a0e38071d793649269520afea7225115-efbefc8af26102fc.elb.us-east-2.amazonaws.com/iris` I get:
`{"message":"make a prediction by sending a post request to this endpoint with a json payload"}`,
but with `curl http://a0e38071d793649269520afea7225115-efbefc8af26102fc.elb.us-east-2.amazonaws.com`, I get an empty response. I'm using `cortex 26.0`

**Comment by imagine3D-ai** [comment]
Just tried the same with `0.28` and no output is given when calling the load balancer

**Comment by deliahu** [comment]
@imagine3D-ai sending a request to the bare load balancer URL is not expected to respond; the message you got back when sending a request to your API endpoint is correct!

Do you have the custom domain set up now? Can you confirm that `curl a0e38071d793649269520afea7225115-efbefc8af26102fc.elb.us-east-2.amazonaws.com/iris` still works, and then try `curl my.domain.com/iris` (replace `my.domain.com` accordingly)?

**Comment by imagine3D-ai** [comment]
Oh, I see. 

48 hours have passed now for sure, but `curl api.my-domain.net/iris` still gives `curl: (6) Could not resolve host: api.my-domain.net`,
even though `curl http://acbaffb42affb40dab522f6b68467bba-a91cd3894d755e24.elb.us-east-2.amazonaws.com/iris` gives `"message":"make a prediction by sending a post request to this endpoint with a json payload"`. 
Have you received the screenshots by email? Perhaps it is neccessary to do this: https://pk.godaddy.com/help/create-a-subdomain-4080  ?

**Comment by imagine3D-ai** [comment]
> Oh, I see.
> 
> 48 hours have passed now for sure, but `curl api.my-domain.net/iris` still gives `curl: (6) Could not resolve host: api.my-domain.net`,
> even though `curl http://acbaffb42affb40dab522f6b68467bba-a91cd3894d755e24.elb.us-east-2.amazonaws.com/iris` gives `"message":"make a prediction by sending a post request to this endpoint with a json payload"`. After redeploying my cluster, I had to make Alias record change in Route 53, to update the load balancer value. I think that the Alias record changes propagate faster and shouldn’t take 48 hours and if not, should I keep my cluster up for longer, to allow alias change to take place?
> Have you received the screenshots by email? Perhaps it is neccessary to do this: https://pk.godaddy.com/help/create-a-subdomain-4080 ?
> 
> *Also, I haven't yet generated SSL certificate for my custom domain (the skippable section in the tutorial). Could that be causing the problem?

**Comment by deliahu** [comment]
I see.

I don't think creating an A record for a subdomain in GoDaddy is the correct approach. The next thing I would try is to remove the NS records in GoDaddy, and then make new NS records in GoDaddy like before, except this time, instead of using `api.my-domain.net` as the name, try using just `api`. I believe these are equivalent in Google domains, but perhaps that is not the case in GoDaddy (maybe they would treat a name value of `api.my-domain.net` as `api.my-domain.net.my-domain.net`). Perhaps before deleting the current NS records, it could be worth seeing if `curl api.my-domain.net.my-domain.net/iris` works. Although even if it doesn't work, I still think it would be worth trying what I described above.

(please be sure to replace `my-domain` in all examples above)

**Comment by imagine3D-ai** [comment]
I've just updated current NS records to be `api` instead of `api.my-domain.net`.
I tried `curl api.my-domain.net.my-domain.net/iris` (replacing `my-domain` with my actual domain-name), before editing the NS records, but it didn't work.
I've sent the screenshot of the DNS panel to dev@cortex.dev

**Comment by imagine3D-ai** [comment]
It finally worked, after making the `api` NS record change! I get `{"message":"make a prediction by sending a post request to this endpoint with a json payload"}` when calling `curl api.my-domain.net/iris`

**Comment by deliahu** [comment]
Awesome!! @miguelvr gets all the credit, it was actually his suggestion :)
