### ISSUE TITLE
Allow setting the shared memory (shm) size for TaskAPI

### ISSUE THREAD

**Issue by sevro** [cortexlabs/cortex#2115]
### Description

Allow setting shared memory for TaskAPI similar to other inference APIs.

### Motivation

Currently it is not possible to use more than one PyTorch dataloader to train a model because of the shared memory limits, they fail with the error:

```
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
```

### Additional context

This was previously discussed in "Allow setting the shared memory (shm) size for the API container" #1638.

**Comment by miguelvr** [comment]
this one should be easy, thanks for reporting!
