### ISSUE TITLE
Death dep is not honoured by kubexit if the container died before kubexit started

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#2217]
Kubexit only watches for changes to the graveyard folder. If a container starts and fails before the second container starts, kubexit will not terminate the second container even if it had a death dependency on the first container because the graveyard was updated before the second container even started.

To reproduce the issue, terminate the first container before the second container starts. An easy way to do this is by having an incorrect CMD or ARGs to force the first container to quit as early as possible.

Potential solution:
- update kubexit to watch for changes and then do a pass on all of the tombstones to determine if the graveyard has already been marked with death timestamps.

**Comment by miguelvr** [comment]
This is an issue on kubexit. We are using my fork currently, but we can fork to cortexlabs and make the fix

**Comment by vishalbollu** [comment]
Agreed. The fix shouldn't be too complicated.
