### ISSUE TITLE
GCP support removed?

### ISSUE THREAD

**Issue by amin-nejad** [cortexlabs/cortex#2294]
Hi, I was planning on using this library for deploying a model to GCP but now that I've come back to the project, it seems GCP support has been completely removed? Are there any plans on bringing it back? Is there somewhere I can read more about the problems you were facing (if any) and why support was dropped? Thanks

**Comment by ospillinger** [comment]
Yes, GCP support has been removed. We definitely want to bring it back but we are focusing our efforts on ironing out the user experience on AWS for now. It's a lot easier for us to iterate on a single cloud provider while also ensuring that Cortex will be reliable for large-scale production deployments.
