### ISSUE TITLE
Support for AWS virtual GPU plugin for GPU sharing

### ISSUE THREAD

**Issue by creatorrr** [cortexlabs/cortex#2295]
Uses [Nvidia MPS (Multi-process service)](https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf) under the hood.

### Notes:

1. We would need to change the taints for GPU pools for pods scheduling on them
2. However, as MPS cannot isolate GPU memory for each process, we may need to set GPU memory consumption limit in each container to avoid an out of memory issue when running multiple processes in parallel.

### Reference:

https://aws.amazon.com/blogs/opensource/virtual-gpu-device-plugin-for-inference-workload-in-kubernetes/
https://github.com/awslabs/aws-virtual-gpu-device-plugin

**Comment by miguelvr** [comment]
That solution is not production-ready for general use-cases because it does not provide resource encapsulation. Exceeding GPU memory in one pod could lead to the failure of multiple pods using that same GPU.

There is a warning about this in the blog post.
> Be aware that the resource allocation only happens in the scheduler of Kubernetes. There’s no constraint for GPU consumption with containers, which is different from CPU and memory allocation. By default, GPU does not support resource isolation while multiple containers share one GPU.

Their example works because they use the encapsulation provided by TF Serving.

**Comment by creatorrr** [comment]
Right. Yes I agree but it is a relatively easy to use

**Comment by miguelvr** [comment]
We won't add the plugin by default to the cluster. What we can eventually do is to support custom annotations and it becomes the responsibility of the user to manage the plugin
