### ISSUE TITLE
Use server-side apply in k8s helpers

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#234]
### Description

Blocked on API server support (https://github.com/kubernetes/enhancements/issues/555)

Reimplement all `Apply*` functions, and remove all `Update*` functions.

The code in `Apply*()` might look like this: ([k8s.io/apimachinery/pkg/types](https://godoc.org/k8s.io/apimachinery/pkg/types#PatchType))

```go
deployment.TypeMeta = deploymentTypeMeta
objBytes, err := json.Marshal(deployment)
if err != nil {
	return nil, err
}
deployment, err = c.deploymentClient.Patch(deployment.Name, ktypes.ApplyPatchType, objBytes)
```

**Comment by kwiesmueller** [comment]
Hey there,
this came up in a GitHub search for Server-Side Apply.
If you encounter problems or need help with implementing Server-Side Apply, feel free to get in touch with us (wg-api-expression) on the Kubernetes Slack or ping me here.
https://kubernetes.slack.com/archives/C0123CNN8F3
