### ISSUE TITLE
Revisit AWS resource deletion

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#276]
### Description

Should the bucket, cloudwatch log groups and/or cloudwatch metrics be deleted on `cortex.sh uninstall` and/or `cortex delete`? Should it depend on whether Cortex made those resources for the user or the user provided their own? Should the user even be allowed to provide their own?

**Comment by vishalbollu** [comment]
Can't delete metrics. They expire and get deleted automatically. I think we should maintain our current decision to help users Cortex resources but not delete them even if they are Cortex created.
