### ISSUE TITLE
Improve container logging

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#324]
### Description

- [ ] Include all containers and init containers in logs
- [ ] Fix `--previous` implementation
- [ ] Revisit log output formatting
- [ ] Show restarted attempts

**Comment by vishalbollu** [comment]
When an error is encountered while initializing flask container (e.g. exception in python handler), `kubectl logs ... --previous` fails during the transition of pod status from Error to CrashLoopBackOff `Unable to retrieve container logs for docker://<container_id>`
