### ISSUE TITLE
Autoscaling to 0

### ISSUE THREAD

**Issue by nickwalton** [cortexlabs/cortex#443]
Does Cortex support auto scaling down to 0 if there is no current traffic? Couldn't find documentation about auto scaling.

**Comment by ospillinger** [comment]
Yes, you would need to set [min_replicas](https://github.com/cortexlabs/cortex/blob/master/docs/deployments/apis.md) on each API to 0 as well as `export CORTEX_NODES_MIN="0"`. I'll clarify this in the docs.

**Comment by nickwalton** [comment]
Awesome thanks!

**Comment by ospillinger** [comment]
@deliahu corrected me that we can only autoscale down to 1 replica right now because the autoscaler is based on CPU which is undefined when there are no replicas. I'm sorry about the miscommunication and we'll look into how we can support autoscaling to 0.

**Comment by nickwalton** [comment]
Gotcha. Well if you are able to enable it then that would be a great feature. I'll add it as a feature request #445

**Comment by deliahu** [comment]
Thanks @nickwalton, I agree and we'll definitely look into it! According to https://github.com/kubernetes/kubernetes/issues/69687 it should be possible if we use custom metrics for autoscaling instead of CPU utilization.
