### ISSUE TITLE
Can't access s3 example bucket

### ISSUE THREAD

**Issue by nickwalton** [cortexlabs/cortex#446]
I'm not sure if this is how it's meant to be but I'm unable to run the gpt-2 cortex example because of bucket permission issues
`error: cortex.yaml: api: generator: model: s3://cortex-examples/gpt-2/774M/1539234541.zip: not found or insufficient permissions
`

**Comment by deliahu** [comment]
Sorry about that! We are preparing for our release of v0.8 (which does not require zipping the model), and in our haste we deleted the old models when we uploaded the new, non-zipped ones.

We have added back both the small and large GPT-2 models:
* s3://cortex-examples/gpt-2/124M/1539234124.zip
* s3://cortex-examples/gpt-2/774M/1539234541.zip

Please let me know if this fixes the issue!

**Comment by deliahu** [comment]
@nickwalton I am marking this issue as resolved, please follow up if you encounter any more issues.
