### ISSUE TITLE
Explore TensorRT

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#517]
### Description

Use for ONNX, TF Serving, and/or Predictor? Replaces TF Serving?

* https://github.com/NVIDIA/TensorRT
* https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html
* https://github.com/tensorflow/tensorrt

**Comment by miguelvr** [comment]
The Triton Inference Server (fka TensorRT Inference Server) might be a good option as an alternative to Tensorflow Serving, and a more efficient on to serve traced pytorch models with libtorch (no python GIL)

https://github.com/NVIDIA/triton-inference-server

**Comment by deliahu** [comment]
@miguelvr yes that could be a good option. Currently my understanding is that it's possible to serve TensorRT models in TF Serving using our existing stack, but we have not attempted this before. Assuming that is the case, do you think it makes sense to change the title of this ticket to something along the lines of "Support Triton Inference Server"? Since perhaps TensorRT is already supported, and adding support for Triton can be a separate matter (to optimize performance)?

**Comment by miguelvr** [comment]
Yes, I think Triton Inference Server covers more use cases and it is useful to optimize both TF and ONNX models.

It also has the makes sharing models between GPUs of the same machine more efficient.

**Comment by deliahu** [comment]
Sounds good; in that case I'm closing this issue, and I created https://github.com/cortexlabs/cortex/issues/1016.

Thanks for bringing this up!
