### ISSUE TITLE
Official Website?

### ISSUE THREAD

**Issue by tomtom215** [cortexlabs/cortex#53]
Hey there - I was just curious if you have a real website that isn't just a redirect to your repo?

I noticed you have docs and a job posting page but no normal landing page. Is this by default due to stealth launch? Or perhaps issues with SEO as there seems to be another company very close to your naming - https://www.cortexlabs.ai/

Obviously the development is more important but it is always nice to be able to send non-technical/business colleagues a place where they can get an overview without crawling through a repo :)

**Comment by ospillinger** [comment]
Thank you for your feedback! I am working on a landing page and will reply here once it's live.

**Comment by ospillinger** [comment]
The landing page is live at cortex.dev

Have a good weekend!
