### ISSUE TITLE
Deploy Error [failed to connect to the operator]

### ISSUE THREAD

**Issue by nzhiltsov** [cortexlabs/cortex#537]
Hi, I'm getting the following error during `cortex deploy` for any project:

> error: failed to connect to the operator (https://a13a71df9faca11e9ac8aHIDDEN-679HIDDEN.us-west-2.elb.amazonaws.com), run `cortex configure` if you need to update the operator URL

Prior that, I managed to run the cortex examples in my environment on AWS. Then, mistakenly removed the EKS cluster from the console, forgetting about 'cortex.sh uninstall'. Then, managed to clean up the CloudFormation stacks, LB, instances and VPC from the cortex entries. But the environment seems to remain in the inconsistent state. How to make it right again?

**Comment by ospillinger** [comment]
Hey Nikita, `cortex deploy ` will not work without a cluster running the operator. You can make sure that all resources from your previous cluster have been cleaned up by looking at the CloudFormation console. Then, you'll be able to start a new cluster (www.cortex.dev/install), run `cortex configure` to reconnect your CLI to the new operator, and `cortex deploy` should work again.

**Comment by nzhiltsov** [comment]
So, the problem somehow has gone away. Perhaps, there is a time lag on AWS.
