### ISSUE TITLE
Example for tensorflow is not present

### ISSUE THREAD

**Issue by nikkkkhil** [cortexlabs/cortex#605]
### Description
This examle is not present https://github.com/cortexlabs/cortex/tree/0.10/examples/tensorflow/sentiment-analyzer

**Comment by vishalbollu** [comment]
Hi @nikkkkhil that example was renamed from sentiment-analysis in version 0.10 to sentiment-analyzer in version 0.11 which is going to be released soon. 

Can you describe how you ran into that link?

In the meantime, that example can be accessed in the link: https://github.com/cortexlabs/cortex/tree/0.10/examples/tensorflow/sentiment-analysis
