### ISSUE TITLE
Add more visibility to API statuses

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#607]
### Description

Currently API `updating` status abstracts many processes that are happening under the hood e.g.:
- rolling update to update API code or model
- spinning up more instances (the delay is very apparent when scaling from 0)
- scaling down
- updating pod resources
- downloading images

There is no way for the user to determine what `updating` means currently using cortex commands. It can be useful for the user to get more information on how the API is being updated, maybe in cx get <api_name>

**Comment by deliahu** [comment]
Closing due to vagueness
