### ISSUE TITLE
Support fractional GPU requests

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#614]
### Description

Allow users to share a GPU between different models.

### Additional Context
- https://github.com/NVIDIA/nvidia-docker/issues/808
- https://github.com/kubernetes/kubernetes/issues/52757#issuecomment-402772200
- https://aws.amazon.com/blogs/machine-learning/save-on-inference-costs-by-using-amazon-sagemaker-multi-model-endpoints/
- https://stackoverflow.com/questions/55907275/can-multiple-tensorflow-inferences-run-on-one-gpu-in-parallel

**Comment by deliahu** [comment]
Closing in favor of #890 and #619
