### ISSUE TITLE
Perform rolling update of daemonsets on cluster update

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#630]
### Description

Update one daemonset at a time and wait for completion before continuing to not trigger operator cluster autoscaling (in `manager/install.sh`)

Docs: https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/

**Comment by tthebst** [comment]
Hi, 
I will try to work on this one.
I followed the development instructions and now encounter the issue that if I run for example cluster update it used the public images instead of my modified ones. It uses cortexlabs/manager:master instead of my images on aws. Do you know this issue?

Tim

**Comment by RobertLucian** [comment]
@tthebst regarding the error you are getting, yes that's correct. Version `0.15` of Cortex still uses those fields. 

On the `master` version though, you'll see that they've been removed (related to https://github.com/cortexlabs/cortex/pull/948). Check out the `master` version of the [documentation](https://www.cortex.dev/v/master/contributing/development).
