### ISSUE TITLE
Allow users to configure request queue length

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#646]
### Description

Currently, when a waitress queue has reached its `connection_limit` (default 100), the following is returned: `no healthy upstream`. Make `connection_limit` configurable to allow users to customize the length of the queue.

### Additional Context

* May need to expose functionality to configure settings such as connection-idle-timeout in waitress, ELB and other network hops so that these networks don't kill requests while they are waiting in a queue.

**Comment by nickwalton** [comment]
This is super critical for us. So if this can be done as soon as possible would be extremely helpful.
