### ISSUE TITLE
Support inferentia instances

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#654]
#### Description

* https://aws.amazon.com/ec2/instance-types/inf1/
* inferentia [blog post](https://aws.amazon.com/blogs/aws/amazon-ec2-update-inf1-instances-with-aws-inferentia-chips-for-high-performance-cost-effective-inferencing/), [announcement](https://aws.amazon.com/about-aws/whats-new/2019/12/introducing-amazon-ec2-inf1-instances-high-performance-and-the-lowest-cost-machine-learning-inference-in-the-cloud/)

**Comment by RobertLucian** [comment]
@deliahu letting you know I'm going back to this ticket (as we have previously discussed). Been busy with #948 so far. Hope that's okay with you.

**Comment by RobertLucian** [comment]
Useful resources:

- https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-container-tools/tutorial-k8s.md - device plugin to expose inf chips to k8s.
- https://github.com/aws/aws-neuron-sdk/blob/master/FAQ.md - faq on aws neuron sdk.
