### ISSUE TITLE
Short-circuit cortex folder zipping when it gets too large

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#721]
#### Description

Currently, if the contents of the directory (and all subdirectories) that contains `cortex.yaml` is very large (e.g. 5gb), zipping the folder takes a long time. The code that checks for the zip file being too large only runs after the folder is zipped. It would be better if the zipping of the files short-circuited after exceeding a certain size.

If this is difficult to implement, an alternative could be to short-circuit after a certain amount of time.

**Comment by dwanderton** [comment]
Could potentially be done by calling `du -sh` in bash and checking if this value exceeds 50MB.
