### ISSUE TITLE
Read AWS credentials from ~/.aws for cortex_installer.sh and/or CLI

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#73]
### Description

Find a way to use (or ask if the user wants to use) AWS credentials from ~/.aws

### Motivation

* Reduce installation friction
* Users may not want to overwrite environment variables (even though it is shell scoped)

### Additional Context

* How do you know which AWS profile to use?
* Is there a library to read the AWS config?

**Comment by htaidirt** [comment]
Hi @deliahu ,

Got the idea too. Here is a change to `./cortex.sh` to take AWS credentials into account if they are not specifically exported in the shell. Existence of credentials in `~/.aws/credentials` assumes the installation of `aws-cli`, which offers the way access used credentials.

Now I admit I tested manually but not with `make test`. I'm not a good Go developer (just have the basics), so I was getting a lot of errors for missing packages (cortexlabs/yml, GoogleCloudPlatform/spark-on-k8s-operator,...) How can I install them all at once and not manually? Also do you have a `CONTRIBUTION.md` file for external contributors like me?

Thanks

**Comment by deliahu** [comment]
Thanks for submitting your PR!

Yes, configuring Go environments can be tricky. Since we switched to Go modules, `go` should download the dependencies automatically at build time. For example, I ran the Go tests in a clean docker image with Go v1.12.6:

```
$ docker run --rm -it golang:1.12.6
root@9c1fd142baf1:/go# git clone https://github.com/cortexlabs/cortex.git
Cloning into 'cortex'...
...
root@9c1fd142baf1:/go# cd cortex/
root@9c1fd142baf1:/go/cortex# make test-go
go: finding github.com/pkg/errors v0.8.1
...
go tests passed
```

Note that the Python tests won't run here since they run in Docker (and I didn't configure "Docker in Docker"), however they should run on your local environment if you have Docker installed. `make test` runs all of the tests.

We do have a guide for setting up a development environment, which we will make more prominent soon: https://github.com/cortexlabs/cortex/blob/master/docs/cluster/development.md

Also, CI runs the tests and makes sure all of the images build on each push. You can get a link to the job on CircleCI at the bottom of [your PR](https://github.com/cortexlabs/cortex/pull/303) in the "All checks have passed" section (in this case: https://circleci.com/workflow-run/f54fa603-c361-469e-b795-728a138f54c6).
