### ISSUE TITLE
Add cortex commands to list and remove CLI environments

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#730]
Multiple CLI environments can be created with `cortex configure -e <environment_name>`. Adding cortex commands to list the available environments and delete them would help with CLI environment management.

**Comment by RobertLucian** [comment]
@vishalbollu I'd like to work on this issue. What do you think?

**Comment by vishalbollu** [comment]
@RobertLucian Go for it! We can schedule a call to decide on a potential interface when you get to that stage.

Some options:
```bash
cortex configure --env # -e
cortex configure --list # -l
cortex configure --remove # -rm

cortex configure env
cortex configure list
cortex configure remove
```

I moved one of the requirements (remove associated CLI environments after a `cortex cluster down`) to #894  because it isn't related to the core of this issue.
