### ISSUE TITLE
Add name length validations, support longer names

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#732]
#### Description

Currently, `cortex deploy` fails in the background if names are too long (e.g. > 63 characters) due to kubernetes label length limits. There should be cortex validations that check this.

In addition, the log group name label is the concatenation of log group, app name, and API name. This should be shortened

**Comment by HowJMay** [comment]
Does the name here mean CONFIG_FILE name?

**Comment by vishalbollu** [comment]
Hi @HowJMay this ticket refers to the preventing Cortex from assigning labels that are longer than 63 characters to Kubernetes pods. Some of the labels are being generated are based on users' deployment configuration in their cortex.yaml. This ticket is being addressed by PR #751. There are other tickets that we can use your help with which we labeled as [good first issue](https://github.com/cortexlabs/cortex/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). Feel free to message us on [gitter](https://gitter.im/cortexlabs/cortex) if you have any questions.

**Comment by HowJMay** [comment]
Oh got it! Thank you
