### ISSUE TITLE
How to install???

### ISSUE THREAD

**Issue by Jie-Yuan** [cortexlabs/cortex#762]
#### Version

(use `cortex version` to determine your version)

#### Description

(describe the bug)

#### Configuration

(paste relevant `cortex.yaml` or `cluster.yaml` configuration)

#### Steps to reproduce

1. ...
2. ...
3. ...

#### Expected behavior

(describe the behavior you expected)

#### Actual behavior

(describe the behavior you experienced)

#### Screenshots

(optional)

#### Stack traces

(error output from `cortex logs <api name>`)

```text
<paste stack traces here>
```

#### Additional context

(optional)

#### Suggested solution

(optional)

**Comment by ospillinger** [comment]
The installation instructions are here: https://www.cortex.dev/install.
