### ISSUE TITLE
Make slim versions of serving images

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#781]
#### Description

Serving images such as `python-serve`, `python-serve-gpu` have a lot of python packages and system libraries to make onboarding easy. 

Have a slim version that only contains the python packages and system libraries to run Cortex serving.

#### Motivation

Having unnecessary libraries in docker images can increase storage costs and also network costs.

**Comment by tthebst** [comment]
Hi,

What's the reason for using conda inside ubuntu and not a python docker image?

**Comment by deliahu** [comment]
Hi @tthebst, the intention of this is provide a base image that has all of the Cortex code in it, but without any of the "user" dependencies installed. Right now our containers ship with PyTorch, TensorFlow, Scikit Learn, XGboost installed, whereas a user probably only needs one of these. So if they are interested in building their own image from our "base" image and using that, or if they are ok `pip install`ing their dependencies every time an API replica is created, they would want to use the "slim" base image. It would still be based on Ubuntu and still have conda, just wouldn't have the extra pip packages.

We are planning to add these images soon!

**Comment by tthebst** [comment]
Okay I understand. So you would like just a slim image with just the dependencies needed for cortex, but still based on ubuntu and conda?

**Comment by deliahu** [comment]
@tthebst yes that is correct. I just created a pull request for this: https://github.com/cortexlabs/cortex/pull/992; we'll merge it soon and it will be in our next release!
