### ISSUE TITLE
Add CLI command to exec into running api pod

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#791]
Command: `cortex debug exec API_NAME`

Behavior: choose a running API pod (at random is ok if there are multiple), and run e.g. `kubectl exec -it api-iris-classifier-6d866654f8-pwz62 --container api -- /bin/bash`

This command should be executed in the manager container, similar to how the `cortex cluster up` command works. However unlike `cortex cluster up`, this command will require interactivity with the terminal so the user can execute shell commands in the container.

The relevant code for `cortex cluster up` is `runManager()` in `cli/cmd/lib_manager.go`: https://github.com/cortexlabs/cortex/blob/master/cli/cmd/lib_manager.go#L42

**Comment by sohaib-omar** [comment]
is this issue still open to pick?

**Comment by miguelvr** [comment]
> is this issue still open to pick?

feel free to contribute! this would be a cool one
