### ISSUE TITLE
Interface to other Cloud Providers?

### ISSUE THREAD

**Issue by mmortazavi** [cortexlabs/cortex#802]
I really like the clean interface and simple use. Great job! I am just wondering, are there any plans to extend Cortex functionalities to other major cloud providers: Microsoft Azure, Google Cloud Platform?

**Comment by vishalbollu** [comment]
@mmortazavi Adding support for other cloud providers is on the roadmap with GCP being our next priority. Are there particular features from other cloud providers that you would like to see Cortex support when we add support for other cloud providers?

I'd be happy to jump on a call to discuss if you'd like, feel free to email me at vishal@cortexlabs.com.

**Comment by mmortazavi** [comment]
@vishalbollu Thanks for the quick reply. Nothing special, simple functionalities like you do provide for AWS for deployment would be a great start, things like launching/terminating instances, Autoscaling, Remote debugging, Docker, Kubernetes, packages you have a great list I am currently focused on a containerized TF Object Detection model.

**Comment by vishalbollu** [comment]
If you don't mind me asking, which cloud provider(s) are you using for your model serving? As we set our roadmap, it's helpful for us to know which clouds our users prefer and why.

If you are interested in object detection, you may want to check out https://github.com/cortexlabs/cortex/pull/803 showcasing a real-time video-based license plate detection based on models like yolov3 and how to deploy with Cortex.

**Comment by mmortazavi** [comment]
Sure. We are mainly based on Microsoft Azure, but starting to explore options at AWS and GCP! I would rather keep our services for now in one place, our primary provider Azure, running the API, containers etc. to have easier control over our resources, others access to GCP and AWS is there too. 

I will have a look at the detection example, thanks!

**Comment by vishalbollu** [comment]
Thanks for letting us know. It makes sense to lean towards existing infra but still be on the lookout for other tools that may increase productivity.

Support for GCP is being tracked in https://github.com/cortexlabs/cortex/issues/114 and Azure in https://github.com/cortexlabs/cortex/issues/811.

Let us know if you have any questions, feel free to close this ticket otherwise.
