### ISSUE TITLE
Example rough costs in README or elsewhere

### ISSUE THREAD

**Issue by bcjordan** [cortexlabs/cortex#806]
#### Description

I'm not sure if this is already available elsewhere—it would be very helpful for those considering deployment options to see a rough total cost estimate of what cortex examples' deployments look like before going through the tutorial / deploying an example.

I understand these costs fluctuate, but even knowing that a single deployment will cost e.g. on order of single dollars or thousands of dollars would be helpful!

#### Motivation

This would increase users' confidence in getting set up with the system as they can compare the cost to other options.

#### Example output from `cortex cluster up`

````
aws resource                             cost per hour
1 eks cluster                            $0.10
1 20gb ebs volume for the operator       $0.003
1 t3.medium for the operator             $0.0416
1 nat gateway                            $0.045
2 elastic load balancers                 $0.025 each
1 - 5 50gb ebs volumes for your apis     $0.007 each
1 - 5 t3.small instances for your apis   $0.0208 each

this cluster will cost $0.27 - $0.38 per hour based on the cluster size
````

**Comment by bcjordan** [comment]
I see https://www.cortex.dev/cluster-management/ec2-instances covers at the per-hour level during the tutorial

**Comment by deliahu** [comment]
@bcjordan yes I think this is a great idea, we'll work on adding this today

**Comment by deliahu** [comment]
@bcjordan I've made a PR to address this: https://github.com/cortexlabs/cortex/pull/807

Is this what you had in mind? Let us know if you'd like us to change or add something!

(feel free to check just the .md files and ignore the diff in the go file, I just rearranged the cost breakdown table a bit)

**Comment by bcjordan** [comment]
Looks great, thanks!

**Comment by bcjordan** [comment]
Looks great, thanks!
