### ISSUE TITLE
Support Azure

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#811]

**Comment by asonee-omnipresence** [comment]
Hi, what is the time for Azure support?

**Comment by ospillinger** [comment]
We don't have immediate plans to support Azure. That being said, we plan to support GCP within the next few releases so that should help inform our timeline for Azure support.

**Comment by ymsahala** [comment]
Looking forward for this enhancement.

**Comment by vishalbollu** [comment]
We are focusing on AWS at the moment and supporting Azure is not in our near term roadmap.
