### ISSUE TITLE
Add request timeout configuration

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#824]
#### Description

Add a config field for API request timeout. If the timeout is exceeded, the server should respond with an error code, and the request should stop being processed.

A reasonable first-pass solution could be to check the request start time in the API server, and return error code 408 it it's been longer than the timeout (skipping processing).

Note that if the user is using API gateway, the max timeout will be 29 seconds.

**Comment by vishalbollu** [comment]
Consider having a process in request-monitor.go to delete request files older than the request timeout configuration to ensure that any mistakes in deleting request files in API pod are cleaned up.

**Comment by deliahu** [comment]
Closing since with the current architecture, there is no request time limit
