### ISSUE TITLE
Support autoscaling based on GPU metrics

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#837]
#### Description

Support autoscaling based on GPU metrics like temperature.

#### Motivation 

This may be necessary for cases where overheating GPUs cause replicas to become unresponsive, since this may happen even without queue build-up

Blocked on https://github.com/cortexlabs/cortex/issues/836

**Comment by salanki** [comment]
Over-heating GPUs sounds like a bad node. Better to work around this with a powerlimit on the GPU rather than trying to limit requests.

**Comment by deliahu** [comment]
Closing since request-based scaling is supported and should work well for GPU-based workloads
