### ISSUE TITLE
Support multi-model endpoints for TensorFlow and ONNX predictors

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#890]
Currently muti-model endpoints is only supported for the Python predictor type. Support should be added for the TensorFlow and ONNX types.

#### Potential design

Add a `models` key to the API configuration, which is a map of model name -> model path. Then, models could be accessed by the TensorFlow/ONNX client by name, e.g. `client.predict("model-1")`

#### Motivation

Share GPU resources across multiple models

**Comment by RobertLucian** [comment]
@deliahu taking this one alongside https://github.com/cortexlabs/cortex/issues/619. Finally, guides for each predictor type will be required as described in https://github.com/cortexlabs/cortex/issues/986.
