### ISSUE TITLE
Explore k8s pod descheduler

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#928]
#### Motivation

Reschedule pods on underutilized nodes to "pack them in" better

#### Questions

* Does the cluster autoscaler perform this action, or is it necessary to add this add-on?

#### Additional context

* https://github.com/kubernetes-sigs/descheduler
* https://itnext.io/the-definitive-guide-to-running-ec2-spot-instances-as-kubernetes-worker-nodes-68ef2095e767

**Comment by vishalbollu** [comment]
The cluster autoscaler reshuffles nodes based on node utilization.
