### ISSUE TITLE
Managing Multiple Clusters with CLI

### ISSUE THREAD

**Issue by wise-east** [cortexlabs/cortex#943]
#### Description

I'm sorry if this is a duplicate of an issue that is already available, but I couldn't quite find one that was exactly discussing what I am mentioning here. This is sort of a question + request for feature if there is no support for this functionality. 

I was able to successfully spin up a new cluster on top of another one on the same account and region, and also deploy an API to the new cluster, but I'm wondering what the CLI commands are for managing both at the same time. I can use `cortex cluster info` and provide info about a running cluster and get information about it, but when I use `cortex get`, I only get API information for the new cluster, but none for the first cluster I spun up. 

Is there a way to switch the cluster that I am accessing with `cortex get`, or have all the APIs show up with each of their respective cluster that they are deployed on using `cortex get`?

This is important if I want to compare the average request time to decide which cluster best suits my use-case and spin down inferior clusters. 

#### Motivation

I'm spinning up various clusters that are using different instances to check the performance of my API on different GPUs and determine which is the best value for money. The API is exactly the same, just being deployed on different clusters. This might be a niche situation and a feature not worth prioritizing, but I think it might actually be frequently observed for users who are not familiar with what instance best suits their use-case.

**Comment by deliahu** [comment]
@wise-east Yes we support the `--env` flag on most `cortex` commands to allow the CLI to connect with multiple clusters. I will create a proper guide on this, but I have to head out now, so in the mean time here is a quick version (to make it simpler I'll assume one CPU cluster and one GPU cluster):

If you are spinning up new clusters, the easiest way would look something like this:

1) `cortex cluster up --env gpu --config cluster-gpu.yaml`
2) `cortex cluster up --env cpu --config cluster-cpu.yaml`
3) `cortex deploy --env gpu` (will deploy the API to the gpu cluster)
4) `cortex deploy --env cpu` (will deploy the API to the cpu cluster)

If you already have a cluster running, or forget the `--env` flag on `cortex cluster up`, you can do something like this:

1) `cortex cluster info --config cluster-gpu.yaml` (will show you the operator url for the gpu cluster)
2) `cortex configure --env gpu` (use the operator URL from step 1)
3) `cortex cluster info --config cluster-cpu.yaml` (will show you the operator url for the cpu cluster)
4) `cortex configure --env cpu` (use the operator URL from step 3)
5) `cortex deploy --env gpu` (will deploy the API to the gpu cluster)
6) `cortex deploy --env cpu` (will deploy the API to the cpu cluster)

**Comment by wise-east** [comment]
Thank you! I suspected the --env flag to be of use here but it wasn't clear with the current docs. Thank you for the steps!
