### ISSUE TITLE
What is the minimal policy/permission for IAM account to spin up cluster?

### ISSUE THREAD

**Issue by wise-east** [cortexlabs/cortex#944]
I'm wondering if there is a minimal AWS permission policy that you can provide for setting up IAM users that can run the `cortex cluster up` command without failing due to permission issues. Due to financial reasons, I set up an IAM for an account that I don't have root access to, and I had difficulty requesting the minimal permissions for spinning up the clusters. It seemed any set of the pre-existing AWS policies was not able to give me the right permissions for setting up the cluster (getting caught for things like iam:CreateRole", and much more).  After multiple trial-and-errors and some research, I set up a custom AWS permission policy with JSON that allows me to do all the things I need: 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:*",
                "eks:*",
                "ec2:*",
                "elasticloadbalancing:*",
                "cloudwatch:*",
                "autoscaling:*",
                "cloudformation:*",
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "apigateway:*",
                "s3:*",
                "logs:*",
                "events:*",
                "cognito-idp:DescribeUserPoolClient"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "iam:AWSServiceName": [
                        "autoscaling.amazonaws.com",
                        "ec2scheduled.amazonaws.com",
                        "elasticloadbalancing.amazonaws.com",
                        "spot.amazonaws.com",
                        "spotfleet.amazonaws.com",
                        "transitgateway.amazonaws.com"
                    ]
                }
            }
        }
    ]
}
```

This can be used to make a custom policy by pressing `Create Policy` here: 
![Screen Shot 2020-04-03 at 12 48 45 AM](https://user-images.githubusercontent.com/31977186/78336899-f82ac580-7544-11ea-878e-b9562ccfff95.png)
and choosing the JSON tab and inserting it there. 

However, I am certain that this is not the minimal permissions that can be given, as I have used the `*` symbol so that I don't have to add individual policies each time I fail to spin up the cluster. I think providing a minimal set of permissions in the format above can be useful for users like me who don't have access to the root account, as it took me a while to able to list out all the requirements. I thought I would be able to find detailed information for this at: https://www.cortex.dev/cluster-management/security#iam-permissions, but I guess the docs were not ready yet. In the meantime, I think future users can use this if they want to set up an IAM without the full admin permission. 

Just FYI, I also realized that when I fail on certain levels, towards the beginning of setting up the cluster, I had to manually delete the stack on CloudFormation and the CloudWatch log group to be able to run `cortex cluster up` again.

**Comment by deliahu** [comment]
@wise-east thanks for sharing this!

> I'm wondering if there is a minimal AWS permission policy that you can provide for setting up IAM users that can run the cortex cluster up command without failing due to permission issues...  I think providing a minimal set of permissions in the format above can be useful for users like me who don't have access to the root account, as it took me a while to able to list out all the requirements.

We have not identified this "minimal" policy since the CLI requires many permissions (as you noticed), and it's difficult to create an exhaustive list since the requirements may change as Cortex adds new features. Is it possible for you to add the `AdministratorAccess` policy to your IAM user? Also in case it helps (as mentioned in the docs you referenced), you can use credentials with fewer permissions for the cluster itself.

> After multiple trial-and-errors and some research, I set up a custom AWS permission policy with JSON that allows me to do all the things I need

That's awesome! Has the cluster been fully functional thus far? I'm considering adding your list to the docs, however my main concern is that over time as we add new features, this list may change and we'll have to invest in keeping it up to date (and in reality it may not be much "lighter" than the `AdministratorAccess` anyways).

> However, I am certain that this is not the minimal permissions that can be given

Yes you are correct

> Just FYI, I also realized that when I fail on certain levels, towards the beginning of setting up the cluster, I had to manually delete the stack on CloudFormation and the CloudWatch log group to be able to run `cortex cluster up` again.

Yes, this is a known behavior. We try to mention how to clean this up manually in the error message, since in some scenarios it's difficult to do in an automated way. We improved the error messages a bit in v0.15, and we added a check to see if the IAM user has `AdministratorAccess` to help avoid this situation. Should we make any of the error messages or warnings more clear? Perhaps the `AdministratorAccess` warning could include instructions on how to add the policy to your IAM user?

**Comment by wise-east** [comment]
> That's awesome! Has the cluster been fully functional thus far? I'm considering adding your list to the docs, however my main concern is that over time as we add new features, this list may change and we'll have to invest in keeping it up to date (and in reality it may not be much "lighter" than the AdministratorAccess anyways).

It has been fully functional so far, and if I recall correctly these will also allow for these steps to be taken with the IAM account as well: https://www.cortex.dev/guides/api-gateway 

I agree on your concern and it might not be that useful in the longer run, but maybe useful for the short term. In addition, the action configuration `iam:*` actually defeats the purpose of setting up an IAM because then the IAM user can change his/her policy to allow for `AdministratorAccess`. 

> Yes, this is a known behavior. We try to mention how to clean this up manually in the error message, since in some scenarios it's difficult to do in an automated way. We improved the error messages a bit in v0.15, and we added a check to see if the IAM user has AdministratorAccess to help avoid this situation. Should we make any of the error messages or warnings more clear? Perhaps the AdministratorAccess warning could include instructions on how to add the policy to your IAM user?

I think the error messages were pretty clear even in v0.14, and I haven't checked the error messages that would appear in v0.15 so I can't give the best opinion on this. For those who are not familiar with setting policies for IAM users may find the instructions useful, but my concern is that it would lead to an iterative and cumbersome process where you add individual policies such as "iam:CreateRole", delete the stack and log group, and then rerun `cortex cluster up` just to find out that you have to add "iam:<some other function>" and repeat the same process. Maybe an error message saying "You're likely getting this error message because you don't have the full list of permissions for spinning up this cluster. Please make sure that the IAM user you are using to spin up the cluster has `AdministratorAccess` or all of the following permissions: `<link to the configuration that I provided above or instruction on adding it>`" will save the user from the pain I had to go through.
