### ISSUE TITLE
Remove user-facing images from cluster.yaml

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#950]
#### Description

Move docker image paths from `cluster.yaml` to `cortex.yaml`. Thanks, @deliahu, and @vishalbollu for thinking about this. 

#### Motivation

Since #900 allows setting images on a per-API basis, keeping the afferent fields in the cluster config doesn't make much sense, because, at this idea's core, images are supposed to be set on an API basis. 

The other advantage of setting them in the API is that the user has more granular control over what API uses what resource. And regardless, if users leave the fields empty (in the API config), they will get the default paths anyway.

**Comment by deliahu** [comment]
@RobertLucian I think we may want to fold this into https://github.com/cortexlabs/cortex/issues/900, what do you think?

**Comment by RobertLucian** [comment]
@deliahu yep, totally agree.

**Comment by deliahu** [comment]
Keeping it as a separate ticket is totally ok! I was just thinking https://github.com/cortexlabs/cortex/issues/900 should close both 👍 (which it sounds like your were too)

**Comment by RobertLucian** [comment]
Oh yeah, definitely. Both of them are gonna be closed at the same time.
