### ISSUE TITLE
Add post_predict() function to predictor API

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#954]
#### Description

Add `post_predict()` to the Predictor API for any actions that should be taken after the request has been responded to.

#### Questions

* What information should be passed in? Probably the input and return value of `predict()`.

#### Motivation

Some potential user tasks (e.g. sending metrics, updating in-memory cache, etc) do not have to be on the critical path of responding to the request, so running them after the response is sent will decrease total latency.

**Comment by Charlitos96** [comment]
Hi @deliahu, I'm looking for an Issue to do my first contribution, can you give me more details about what you want to do in `post_predict()`??
Also, can you confirm me that the file to be modified is this [predictor.py](https://github.com/cortexlabs/cortex/blob/dd9d8b3967f1046489253dfeb82ed0b408ef2f71/pkg/workloads/cortex/lib/type/predictor.py) ?

**Comment by deliahu** [comment]
@Charlitos96 I appreciate your interest in contributing!

Yes, we will need to add `post_predict()` as an optional function in `PYTHON_CLASS_VALIDATION`, `TENSORFLOW_CLASS_VALIDATION`, and `ONNX_CLASS_VALIDATION` in [predictor.py](https://github.com/cortexlabs/cortex/blob/master/pkg/workloads/cortex/lib/type/predictor.py#L166) (you can add a new top-level key to the dictionary, similar to "required", but called "optional"). Then the validation should be automatically handed.

I think a reasonable schema is:

```python
***_CLASS_VALIDATION = {
    "required": [
        # ...
    ],
    "optional": [
        {
            "name": "predict",
            "required_args": ["self"],
            "optional_args": ["response", "payload", "query_params", "headers"],
        },
    ],
}
```

Where the args are the same as `predict()`, plus it also includes the return value from `predict()` (called `response`). Do you think that makes sense?

Then, the user's `post_predict()` function will be added to the [background tasks](https://www.starlette.io/background/) (if it's defined) in [serve.py](https://github.com/cortexlabs/cortex/blob/master/pkg/workloads/cortex/serve/serve.py#L184) at some point after `predictor_impl.predict(**args)` (since we need to pass in the result). We currently only add background tasks if monitoring is enabled (see [here](https://github.com/cortexlabs/cortex/blob/master/pkg/workloads/cortex/serve/serve.py#L210-L213)), so the logic of setting the background tasks in `predict(request: Request)` will have to be updated a little, but not much. 

Finally, we will need to update the docs, specifically [predictors.md](https://github.com/cortexlabs/cortex/blob/master/docs/deployments/predictors.md).

Does that all make sense? Let us know if you have additional questions!
