### ISSUE TITLE
Add "0 To ML App In 15 Minutes Section" tutorial

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#956]
#### Description

Currently, the tutorial uses a not-very-practical model (iris-classifier), and ends with `curl`. Consider adding or replacing with a full end-to-end guide, which includes calling a Cortex API from an application, e.g. “0 to NLP App in Less Than 15 Minutes”. Also consider linking to https://curl.trillworks.com/ for how to convert the `curl` to the appropriate http library

**Comment by ssami** [comment]
@deliahu I've been working with a fastText genre-classification model built on Kaggle's Google books reviews dataset, and wanted to use Cortex to deploy the model. I had some suggestions about improving the doc, as well. Would this sort of project be appropriate for this issue?

**Comment by deliahu** [comment]
@ssami Yes I think it could work well! Is there a sample application from which you plan to call the API?

Also, yes, please share any suggestions you have for improving our docs, thank you! Feel free to email me at david@cortex.dev if you'd like to chat live, or you can create a GitHub issue, whichever you prefer.

**Comment by ssami** [comment]
Thanks @deliahu, I've submitted an issue to enhance documentation [here](https://github.com/cortexlabs/cortex/issues/1098). For the sample application, I am planning to classify the trainng data that isn't labeled with any genre by calling the local deployed classifier API.

**Comment by deliahu** [comment]
@ssami thanks for creating a ticket for the documentation!

That makes sense. I think it might also be cool to have a higher level application consume that API, but I'm not sure exactly what that would look like (maybe a chrome extension that tracks what kinds of things you are reading?), and I wouldn't want you to do extra work that you weren't planning on doing anyways.

We'd be happy to consider adding your project to our [examples](https://github.com/cortexlabs/cortex/tree/master/examples) folder, and potentially consider creating a guide or a blog post as well. Keep us posted on our progress, and let us know if you have any questions/feedback with Cortex!

**Comment by deliahu** [comment]
Closing now that the [tutorial](https://docs.cortex.dev/text-generator) has been updated to use pytorch/text-generator
