### ISSUE TITLE
Load a model once and then access it within multiple workers

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#958]
#### Description

Every additional worker in an API needs to load up the specified model. In this process, duplicates of the same model appear in the instance's memory (in GPU's memory or in RAM). Research and implement a solution that will require a model to be loaded once for all workers. 

#### Motivation

This leads to a reduction in memory usage considerably (by a factor of #workers) and also allows loading up models that are considerably big (>8GB) without a performance penalty.

#### Resources

- http://manpages.ubuntu.com/manpages/bionic/man1/alt-nvidia-340-cuda-mps-control.1.html - ? to be verified
- https://github.com/pytorch/pytorch/issues/16943#issuecomment-463118535

**Comment by hammacktony** [comment]
[Ray](https://github.com/ray-project/ray) solves this by using the Plasma object store. Maybe something like this could be used.

**Comment by RobertLucian** [comment]
That's interesting @hammacktony. I'll have a look at this. Thanks for letting us know about it!

**Comment by arch1902** [comment]
What is the recommended solution for this issue ? I want to implement something similar.

**Comment by tobiaswuerth** [comment]
no solution for windows yet?
