### ISSUE TITLE
How is Cortex different from Streamlit?

### ISSUE THREAD

**Issue by cabhijith** [cortexlabs/cortex#959]
Hi, 
Great project. Really easy to use. Had a doubt in mind. How is Cortex different from Streamlit? Are they similar projects? 

Since I am pretty new to this field, wanted to know the difference? 

Cheers!

**Comment by ospillinger** [comment]
Thanks @cabhijith!

Cortex takes ML models and turns them into scalable web services that you can use in production. Streamlit seems to be focused on helping you create visualizations.

**Comment by cabhijith** [comment]
Thanks!
