### ISSUE TITLE
Support single port for local deployments

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#961]
#### Description

Currently, each local API runs on its own port. Implementing this would allow all endpoints to run on a single port.

For example, two APIs could be running on `localhost:8080/my-api-1` and `localhost:8080/my-api-2`

#### Motivation

This would be more convenient for users who are looking to expose a public port on a cloud instance, e.g. to run a Cortex on a single node.

#### Design

It will likely be necessary to use a separate container to route requests to the appropriate model, e.g. NGINX. This probably would be created manually by the CLI (`docker compose` may be an option as well).

**Comment by kmrabhay** [comment]
Hey, This would be great . @deliahu  May I know if this enhancement is incorporated? Can you guide me on nginx set up with cortex?

**Comment by deliahu** [comment]
@kmrabhay currently this is not incorporated into Cortex, but configuring a single port as an entrypoint for all APIs can be done outside of Cortex. There are a few ways this could be accomplished, I'd be happy to advise; do you mind sharing what cloud platform you're running on (if applicable) and your use case (including how many APIs you will have, whether you'll be continuously adding APIs or if it's a static set, etc)?

**Comment by deliahu** [comment]
@kmrabhay I just wanted to follow up on this, were you able to get it working? Let me know if you'd like any help.

**Comment by dsuess** [comment]
I am interested in this feature as well. Our use case is that we have multiple models (where the output of one model is used for another model) and the deployments reference each other just using a different endpoint. Everything works fine in AWS, but we can't test this setup locally since we can't have multiple endpoints locally without setting a separate port.

**Comment by RobertLucian** [comment]
@dsuess we could bump up the priority for this one and try to get it out of the door. Is this lack of feature a deal-breaker for you?

**Comment by deliahu** [comment]
@dsuess Another thing we could try, if you think it would be helpful, is to see if we could create a guide that shows how to use e.g. NGINX (possibly also running in a docker container) to act as a reverse proxy for locally deployed Cortex APIs. With this guide-based approach, it wouldn't be "built-in" to Cortex, so it would require running NGINX separately, as well as manually updating the NGINX config when APIs are created or deleted. I have not tried this, but it seems to me like it should be possible.

**Comment by dsuess** [comment]
Thanks for your quick reply!

@RobertLucian Not the highest priority on my list, so no need to rush it
@deliahu I think that's a good idea, even independently from this issue. We've used nginx to add https-support to a local deployment. But as means to debugging a complex deployment locally, a solution that behaves similar to AWS would be very useful

**Comment by vishalbollu** [comment]
Closing because local is no longer supported
